import {useEffect,useState} from 'react';
import {FileText,Plus,Trash2,ExternalLink,Download,Upload,Folder,FolderPlus,ChevronRight,Home} from 'lucide-react';
import {supabase} from './lib/backend';
import {toast} from 'sonner';
type Doc={id:string;title:string;description:string;category:string;url?:string;storage_path?:string;folder_id?:string|null;created_by:string;created_by_name?:string;created_at:string};
type FolderItem={id:string;name:string;parent_id:string|null;category:string;created_by_name?:string};
const cats=['Tous','Administration','Réunions','Actions','Communication','Voltigeurs','Modèles','Trésorier','Autre'];
export default function DocumentsPortal({canWrite=false}:{canWrite?:boolean}){
 const [items,setItems]=useState<Doc[]>([]),[cat,setCat]=useState('Tous'),[open,setOpen]=useState(false),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[category,setCategory]=useState('Administration'),[url,setUrl]=useState(''),[file,setFile]=useState<File|null>(null),[saving,setSaving]=useState(false),[folders,setFolders]=useState<FolderItem[]>([]),[folderId,setFolderId]=useState<string|null>(null),[newFolder,setNewFolder]=useState(''),[folderOpen,setFolderOpen]=useState(false);
 async function load(){if(!supabase)return;const [{data,error},{data:fs,error:fe}]=await Promise.all([supabase.from('ca_documents').select('*').order('created_at',{ascending:false}),supabase.from('ca_document_folders').select('*').order('name')]);if(error||fe)toast.error('Impossible de charger les documents.');else{setItems((data||[]) as Doc[]);setFolders((fs||[]) as FolderItem[])}}
 useEffect(()=>{void load()},[]);
 async function save(e:React.FormEvent){e.preventDefault();if(!supabase||saving)return;setSaving(true);try{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:m}=await supabase.from('ca_members').select('display_name').eq('user_id',user.id).maybeSingle();const clean=url.trim();if(clean){try{const u=new URL(clean);if(!['https:','http:'].includes(u.protocol))throw Error()}catch{return toast.error('Le lien doit être une adresse http ou https valide.')}}let storage_path:string|null=null;if(file){if(file.type!=='application/pdf')return toast.error('Seuls les fichiers PDF sont acceptés.');if(file.size>15*1024*1024)return toast.error('Le PDF ne doit pas dépasser 15 Mo.');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');storage_path=user.id+'/'+Date.now()+'-'+safe;const {error:up}=await supabase.storage.from('ca-documents').upload(storage_path,file,{contentType:'application/pdf'});if(up)return toast.error('Import du PDF impossible : '+up.message)}const {error}=await supabase.from('ca_documents').insert({title:title.trim(),description:description.trim(),category:cat==='Tous'?category:cat,url:clean||null,storage_path,folder_id:folderId,created_by:user.id,created_by_name:m?.display_name||user.email});if(error){if(storage_path)await supabase.storage.from('ca-documents').remove([storage_path]);return toast.error(error.message)}setTitle('');setDescription('');setUrl('');setFile(null);setOpen(false);toast.success(file?'PDF ajouté aux documents.':'Document ajouté.');await load()}finally{setSaving(false)}}
 async function download(d:Doc){if(!supabase||!d.storage_path)return;const {data,error}=await supabase.storage.from('ca-documents').download(d.storage_path);if(error||!data)return toast.error('Téléchargement impossible.');const u=URL.createObjectURL(data),a=document.createElement('a');a.href=u;a.download=d.storage_path.split('/').pop()?.replace(/^\d+-/,'')||d.title+'.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
 async function remove(d:Doc){if(!supabase||!confirm('Supprimer ce document ?'))return;if(d.storage_path){const {error:se}=await supabase.storage.from('ca-documents').remove([d.storage_path]);if(se)return toast.error('Suppression du PDF impossible : '+se.message)}const {error}=await supabase.from('ca_documents').delete().eq('id',d.id);if(error)toast.error(error.message);else{toast.success('Document supprimé.');await load()}}
 async function createFolder(e:React.FormEvent){e.preventDefault();if(!supabase||!newFolder.trim())return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:m}=await supabase.from('ca_members').select('display_name').eq('user_id',user.id).maybeSingle();const {error}=await supabase.from('ca_document_folders').insert({name:newFolder.trim(),parent_id:folderId,category:cat==='Tous'?'Administration':cat,created_by:user.id,created_by_name:m?.display_name||user.email});if(error)return toast.error(error.message);setNewFolder('');setFolderOpen(false);toast.success('Dossier créé.');await load()}
 const currentFolder=folders.find(f=>f.id===folderId),childFolders=folders.filter(f=>f.parent_id===folderId&&(cat==='Tous'?true:f.category===cat)),shown=(cat==='Tous'?items:items.filter(x=>x.category===cat)).filter(x=>(x.folder_id||null)===folderId);
 return <section className="secretariat-portal"><div className="secretariat-head"><div><p className="eyebrow">RESSOURCES · FFMC 06</p><h1>Documents de l’antenne</h1><p className="subtitle">Retrouver au même endroit les documents, modèles, liens et ressources utiles au CA.</p></div>{canWrite&&!folderId&&<button className="primary" onClick={()=>setOpen(v=>!v)}><Plus size={16}/>Ajouter</button>}</div>
 {open&&canWrite&&<form className="member-invite secretariat-form" onSubmit={save}><div className="secretariat-fields"><label className="wide"><span>Titre</span><input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex. Modèle de déclaration de manifestation"/></label><label><span>Catégorie</span><select value={cat==='Tous'?category:cat} disabled={cat!=='Tous'} onChange={e=>setCategory(e.target.value)}>{cats.slice(1).map(x=><option key={x}>{x}</option>)}</select></label><label className="wide"><span>Fichier PDF</span><input type="file" accept="application/pdf,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><small>{file?file.name+' · '+(file.size/1024/1024).toFixed(1)+' Mo':'PDF uniquement · 15 Mo maximum'}</small></label><label className="wide"><span>Lien externe <em>facultatif</em></span><input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/></label><label className="wide"><span>Description</span><textarea rows={4} value={description} onChange={e=>setDescription(e.target.value)} placeholder="À quoi sert ce document ?"/></label></div><div className="secretariat-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Annuler</button><button className="primary" disabled={saving}>{saving?'Import en cours…':<><Upload size={15}/>Ajouter aux documents</>}</button></div></form>}
 <div className="filters">{cats.map(x=><button key={x} className={cat===x?'chosen':''} onClick={()=>{setCat(x);setFolderId(null)}}>{x}</button>)}</div>
 <div className="document-browser"><div className="document-browser-top"><div className="document-breadcrumb"><button className="text-btn" onClick={()=>setFolderId(null)}><Home size={15}/>{cat==='Tous'?'Documents':cat}</button>{currentFolder&&<><ChevronRight size={14}/><strong>{currentFolder.name}</strong></>}</div>{canWrite&&<div className="document-browser-actions">{folderId&&<button className="primary" onClick={()=>setOpen(true)}><Plus size={16}/>Ajouter un document</button>}<button className="secondary" onClick={()=>setFolderOpen(v=>!v)}><FolderPlus size={16}/>{folderId?'Nouveau sous-dossier':'Nouveau dossier'}</button></div>}</div>{folderOpen&&canWrite&&<form className="document-folder-create" onSubmit={createFolder}><input autoFocus required value={newFolder} onChange={e=>setNewFolder(e.target.value)} placeholder={currentFolder?'Nom du sous-dossier':'Nom du dossier'}/><button className="primary">Créer</button></form>}<div className="document-folders">{childFolders.map(f=><button key={f.id} className="document-folder" onClick={()=>setFolderId(f.id)}><Folder size={28}/><span><strong>{f.name}</strong><small>{folders.filter(x=>x.parent_id===f.id).length} sous-dossier(s) · {items.filter(x=>x.folder_id===f.id).length} document(s)</small></span><ChevronRight size={18}/></button>)}</div>
 <div className="secretariat-list">{shown.length?shown.map(d=><article className="secretariat-card" key={d.id}><div className="record-top"><span className="member-chip">{d.category}</span><FileText size={18}/></div><h3>{d.title}</h3>{d.description&&<p>{d.description}</p>}<footer><small>{d.created_by_name||'FFMC 06'} · {new Date(d.created_at).toLocaleDateString('fr-FR')}</small><div className="secretariat-card-actions">{d.storage_path&&<button className="text-btn" onClick={()=>void download(d)}><Download size={14}/>Télécharger le PDF</button>}{d.url&&<a className="text-btn" href={d.url} target="_blank" rel="noreferrer">Ouvrir <ExternalLink size={14}/></a>}{canWrite&&<button className="text-btn danger" onClick={()=>void remove(d)}><Trash2 size={14}/>Supprimer</button>}</div></footer></article>):<div className="empty"><FileText size={25}/><h3>Aucun document</h3><p>Les ressources ajoutées à l’antenne apparaîtront ici.</p></div>}</div></div></section>
}