import {useEffect,useRef,useState} from 'react';
import {AlertTriangle,MapPin,Navigation,Upload} from 'lucide-react';
import {supabase} from './lib/backend';
import {toast} from 'sonner';
type E={id:string;title:string;event_date:string;route_geojson?:any};
export default function LiveOperation({events,manage}:{events:E[];manage:boolean}){
 const [eventId,setEventId]=useState(events[0]?.id||''),[route,setRoute]=useState<any>(null),[sharing,setSharing]=useState(false),[positions,setPositions]=useState<any[]>([]),[markers,setMarkers]=useState<any[]>([]);
 const mapNode=useRef<HTMLDivElement|null>(null),map=useRef<any>(null),routeLayer=useRef<any>(null),posLayer=useRef<any>(null),markLayer=useRef<any>(null),watch=useRef<number|null>(null),channel=useRef<any>(null);
 async function load(){if(!supabase||!eventId)return;const [{data:p},{data:m},{data:e}]=await Promise.all([supabase.from('team_live_positions').select('*').eq('event_id',eventId),supabase.from('team_live_markers').select('*').eq('event_id',eventId).order('created_at'),supabase.from('team_events').select('route_geojson').eq('id',eventId).single()]);setPositions(p||[]);setMarkers(m||[]);setRoute(e?.route_geojson||null)}
 useEffect(()=>{if(!mapNode.current||map.current)return;let dead=false;(async()=>{if(!document.querySelector('link[data-leaflet]')){const link=document.createElement('link');link.rel='stylesheet';link.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';link.dataset.leaflet='1';document.head.appendChild(link)}const L:any=await new Promise((resolve,reject)=>{const w=window as any;if(w.L)return resolve(w.L);const old=document.querySelector('script[data-leaflet-js]') as HTMLScriptElement|null;if(old){old.addEventListener('load',()=>resolve((window as any).L),{once:true});old.addEventListener('error',reject,{once:true});return}const sc=document.createElement('script');sc.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';sc.dataset.leafletJs='1';sc.onload=()=>resolve((window as any).L);sc.onerror=reject;document.head.appendChild(sc)});if(dead||!mapNode.current)return;map.current=L.map(mapNode.current,{zoomControl:true}).setView([43.70,7.26],10);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map.current);posLayer.current=L.layerGroup().addTo(map.current);markLayer.current=L.layerGroup().addTo(map.current);setRoute((r:any)=>r?{...r}:r)})();return()=>{dead=true;map.current?.remove();map.current=null}},[]);
 useEffect(()=>{if(!supabase||!eventId)return;void load();if(channel.current)void supabase.removeChannel(channel.current);channel.current=supabase.channel('operation-'+eventId).on('postgres_changes',{event:'*',schema:'public',table:'team_live_positions',filter:'event_id=eq.'+eventId},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'team_live_markers',filter:'event_id=eq.'+eventId},()=>void load()).subscribe();return()=>{if(channel.current&&supabase)void supabase.removeChannel(channel.current)}},[eventId]);
 useEffect(()=>{if(!map.current)return;routeLayer.current?.remove();if(route){const L:any=(window as any).L;if(!L)return;routeLayer.current=L.geoJSON(route,{style:{weight:6}}).addTo(map.current);try{map.current.fitBounds(routeLayer.current.getBounds(),{padding:[20,20]})}catch{}}},[route]);
 useEffect(()=>{const L:any=(window as any).L;if(!L)return;posLayer.current?.clearLayers();positions.forEach(p=>L.circleMarker([p.latitude,p.longitude],{radius:10,weight:3}).bindTooltip(p.display_name||'Voltigeur',{permanent:true,direction:'top'}).addTo(posLayer.current!))},[positions]);
 useEffect(()=>{const L:any=(window as any).L;if(!L)return;markLayer.current?.clearLayers();markers.forEach(m=>L.marker([m.latitude,m.longitude]).bindPopup('<strong>'+m.kind.toUpperCase()+'</strong><br/>'+m.label).addTo(markLayer.current!))},[markers]);
 async function share(){if(!supabase||!eventId)return;if(sharing){if(watch.current!==null)navigator.geolocation.clearWatch(watch.current);watch.current=null;const {data:{user}}=await supabase.auth.getUser();if(user)await supabase.from('team_live_positions').delete().eq('event_id',eventId).eq('user_id',user.id);setSharing(false);return}if(!navigator.geolocation)return toast.error('Géolocalisation indisponible.');const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:m}=await supabase.from('ca_members').select('display_name').eq('user_id',user.id).single();watch.current=navigator.geolocation.watchPosition(async p=>{await supabase!.from('team_live_positions').upsert({event_id:eventId,user_id:user.id,display_name:m?.display_name||'Voltigeur',latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,updated_at:new Date().toISOString()});map.current?.setView([p.coords.latitude,p.coords.longitude],Math.max(map.current.getZoom(),15))},()=>toast.error('Position GPS impossible.'),{enableHighAccuracy:true,maximumAge:5000,timeout:15000});setSharing(true)}
 async function importGpx(file:File){if(!supabase||!eventId)return;const xml=new DOMParser().parseFromString(await file.text(),'application/xml');const pts=[...xml.querySelectorAll('trkpt,rtept')].map(n=>[Number(n.getAttribute('lon')),Number(n.getAttribute('lat'))]).filter(x=>x.every(Number.isFinite));if(pts.length<2)return toast.error('Aucun tracé GPX exploitable.');const geo={type:'Feature',geometry:{type:'LineString',coordinates:pts},properties:{}};const {error}=await supabase.from('team_events').update({route_geojson:geo}).eq('id',eventId);if(error)return toast.error(error.message);setRoute(geo);toast.success('Tracé GPX importé et affiché.')}
 async function marker(kind:string){if(!supabase||!eventId)return;navigator.geolocation.getCurrentPosition(async p=>{const label=prompt('Nom / précision du point :')||kind;const {data:{user}}=await supabase!.auth.getUser();if(!user)return;const {error}=await supabase!.from('team_live_markers').insert({event_id:eventId,author_id:user.id,kind,label,latitude:p.coords.latitude,longitude:p.coords.longitude});if(error)toast.error(error.message)},()=>toast.error('Position GPS impossible.'),{enableHighAccuracy:true})}
 return <div><div className="member-admin-head"><div><p className="eyebrow">MODE OPÉRATION</p><h2>Trajet en direct</h2><p className="subtitle">Tracé prévu, positions partagées et points opérationnels.</p></div></div><label>Manifestation / balade<select value={eventId} onChange={e=>setEventId(e.target.value)} style={{width:'100%',padding:12,margin:'8px 0 14px'}}>{events.map(e=><option value={e.id} key={e.id}>{e.title} · {new Date(e.event_date+'T12:00:00').toLocaleDateString('fr-FR')}</option>)}</select></label>{manage&&eventId&&<label className="secondary" style={{display:'inline-flex',cursor:'pointer',marginBottom:12}}><Upload size={16}/> Importer le GPX<input hidden type="file" accept=".gpx,application/gpx+xml" onChange={e=>e.target.files?.[0]&&void importGpx(e.target.files[0])}/></label>}<div ref={mapNode} style={{height:'58vh',minHeight:420,borderRadius:22,overflow:'hidden'}}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginTop:12}}><button className={sharing?'primary':'secondary'} style={{minHeight:70}} onClick={()=>void share()}><Navigation size={22}/>{sharing?'Position partagée · ARRÊTER':'Partager ma position'}</button><button className="secondary" style={{minHeight:70}} onClick={()=>void marker('regroupement')}><MapPin size={22}/>Regroupement</button><button className="secondary" style={{minHeight:70}} onClick={()=>void marker('incident')}><AlertTriangle size={22}/>Incident</button><button className="secondary" style={{minHeight:70}} onClick={()=>void marker('danger')}><AlertTriangle size={22}/>Danger</button></div><p className="login-help">Le partage GPS est volontaire et s’arrête lorsque vous appuyez sur ARRÊTER. N’utilisez pas ces commandes en conduisant.</p></div>
}