import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import type {Session} from '@supabase/supabase-js';
import {ShieldCheck,Mail,LogOut} from 'lucide-react';
import {configured,supabase} from './lib/backend';
import Dashboard from './Dashboard';
import './styles.css';
function App(){const [session,setSession]=useState<Session|null>(null),[checking,setChecking]=useState(configured),[member,setMember]=useState(false),[email,setEmail]=useState(''),[notice,setNotice]=useState(''),[sending,setSending]=useState(false),[fault,setFault]=useState('');
useEffect(()=>{if(!supabase)return;const client=supabase;let alive=true;let revision=0;async function check(s:Session|null){const checkId=++revision;setSession(s);setMember(false);setChecking(true);setFault('');if(s){const {data,error}=await client.from('ca_members').select('user_id').eq('user_id',s.user.id).maybeSingle();if(!alive||checkId!==revision)return;if(error)setFault('Impossible de vérifier votre accès. Réessayez dans un instant.');else setMember(Boolean(data));}if(alive&&checkId===revision)setChecking(false);}
client.auth.getSession().then(({data,error})=>{if(alive){if(error){setFault('La connexion a expiré. Reconnectez-vous.');setChecking(false);}else void check(data.session);}});const {data:{subscription}}=client.auth.onAuthStateChange((_event,s)=>{if(alive)void check(s);});return()=>{alive=false;subscription.unsubscribe();};},[]);
async function requestLink(e:React.FormEvent){e.preventDefault();if(!supabase)return;setSending(true);setNotice('');try{const redirectTo=new URL(import.meta.env.BASE_URL,window.location.origin).href;const {error}=await supabase.auth.signInWithOtp({email:email.trim(),options:{shouldCreateUser:false,emailRedirectTo:redirectTo}});if(error)setNotice('Le lien n’a pas pu être demandé. Vérifiez votre invitation auprès du coordinateur ou réessayez plus tard.');else setNotice('Si votre compte est autorisé, vous recevrez un lien de connexion par mail.');}catch{setNotice('Connexion indisponible. Réessayez plus tard.');}finally{setSending(false);}}
async function logout(){const {error}=await supabase!.auth.signOut();if(error)setFault('Déconnexion impossible. Réessayez.');}
if(session&&member&&!checking)return <><div className="account-bar"><span>{session.user.email}</span><button onClick={logout}><LogOut size={14}/> Se déconnecter</button>{fault&&<span role="alert">{fault}</span>}</div><Dashboard key={session.user.id}/></>;
return <main className="login-page"><div className="login-card"><div className="brand"><span>06</span><div>FFMC<strong>ESPACE CA</strong></div></div><ShieldCheck size={30}/><h1>{!configured?'L’espace se prépare':checking?'Vérification de votre accès…':session?'Accès au CA requis':'Bienvenue dans l’espace CA'}</h1>{!configured?<><p>La connexion des membres et la sauvegarde partagée doivent encore être activées par le coordinateur.</p><p>Les réunions, dossiers et échéances seront accessibles ici une fois cette configuration terminée.</p></>:checking?<p>Un instant, nous vérifions votre connexion.</p>:session?<><p>{fault||'Votre compte est connecté, mais n’est pas autorisé à consulter les informations du CA. Contactez le coordinateur.'}</p>{fault&&<button className="secondary" onClick={()=>location.reload()}>Réessayer</button>}<button className="secondary" onClick={logout}>Se déconnecter</button></>:<><p>Un espace réservé aux membres autorisés du conseil d’administration de la FFMC 06.</p><form onSubmit={requestLink}><label htmlFor="email">Votre adresse mail</label><input id="email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="prenom@exemple.fr"/><button className="primary" disabled={sending}><Mail size={18}/>{sending?'Envoi en cours…':'Recevoir un lien de connexion'}</button></form><p className="login-help">Utilisez l’adresse associée à votre invitation. Aucun mot de passe à retenir.</p>{notice&&<p role="status" className="login-notice">{notice}</p>}{fault&&<p role="alert">{fault}</p>}</>}</div></main>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
