import {useEffect,useState} from 'react';
import {Play,RotateCcw,Square,XCircle,StickyNote} from 'lucide-react';
import {supabase} from './lib/backend';
import {toast} from 'sonner';
type Meeting={id:string;title:string;status:string;due?:string;notes:string;next:string};
type Session={id:string;meeting_id:string;status:string;started_at:string;ended_at?:string;minutes:string;ai_summary?:string};
type Member={user_id:string;display_name:string};
export default function MeetingLive({meetings,canManage,onChanged}:{meetings:Meeting[];canManage:boolean;onChanged:()=>void}){
 const [sessions,setSessions]=useState<Session[]>([]),[members,setMembers]=useState<Member[]>([]),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[editingClosed,setEditingClosed]=useState<string|null>(null),[openAgendaNote,setOpenAgendaNote]=useState<number|null>(null);
 const agendaItems=(meeting?.notes||'').replace(/\\\\n/g,'\n').split('\n').map(x=>x.trim()).filter(Boolean).filter(x=>!x.toUpperCase().includes('ORDRE DU JOUR')).map(line=>{const clean=line.replace(/^[-•]\s*/,'').replace(/^\d+[.)]\s*/, '').trim();const parts=clean.split('||');return {title:(parts.shift()||'').trim(),note:parts.join('||').trim()}}).filter(x=>x.title&&!['DÉCISIONS DU CA','ACTIONS À L’ISSUE DU CA','À compléter pendant la réunion.'].includes(x.title));
 async function load(){if(!supabase)return;const [{data:s},{data:m}]=await Promise.all([supabase.from('ca_meeting_sessions').select('*').order('started_at',{ascending:false}),supabase.from('ca_members').select('user_id,display_name').eq('active',true).order('display_name')]);setSessions((s||[]) as Session[]);setMembers((m||[]) as Member[])}
 useEffect(()=>{void load();const client=supabase;if(!client)return;let timer:number|undefined;const refresh=()=>window.setTimeout(()=>void load(),120);const channel=client.channel('meeting-live-sync').on('postgres_changes',{event:'*',schema:'public',table:'ca_meeting_sessions'},refresh).on('postgres_changes',{event:'UPDATE',schema:'public',table:'ca_proposals'},refresh).subscribe();timer=window.setInterval(()=>void load(),2000);return()=>{if(timer)window.clearInterval(timer);void client.removeChannel(channel)}},[]);
 const live=sessions.find(s=>s.status==='live'),meeting=meetings.find(m=>m.id===(live?.meeting_id||selected));
 async function start(){if(!supabase||!selected)return;setBusy(true);const m=meetings.find(x=>x.id===selected);const attendance=members.length?members.map(x=>'☐ '+x.display_name).join('\n'):'À compléter';const header=['COMPTE RENDU — '+(m?.title||'Réunion du CA'),'Date : '+(m?.due?new Date(m.due+'T12:00:00').toLocaleDateString('fr-FR'):'à compléter'),'Début : '+new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}),'','PRÉSENCES — cocher les membres présents',attendance,'','ORDRE DU JOUR',(m?.notes||'À compléter').replace(/\\\\n/g,'\n'),'','NOTES, DÉCISIONS ET ACTIONS'].join('\n');const {error}=await supabase.from('ca_meeting_sessions').upsert({meeting_id:selected,status:'live',started_at:new Date().toISOString(),ended_at:null,minutes:header},{onConflict:'meeting_id'});setBusy(false);if(error)return toast.error(error.message);toast.success('Réunion lancée.');await load()}
 async function save(id:string,value:string){if(!supabase)return;setSessions(v=>v.map(s=>s.id===id?{...s,minutes:value}:s));const {error}=await supabase.from('ca_meeting_sessions').update({minutes:value}).eq('id',id);if(error)toast.error('Sauvegarde automatique impossible.')}
 async function togglePresent(name:string){if(!supabase||!live||!canManage)return;const unchecked='☐ '+name,checked='☑ '+name;const next=live.minutes.includes(checked)?live.minutes.replace(checked,unchecked):live.minutes.replace(unchecked,checked);await save(live.id,next);}
 async function finish(){if(!supabase||!live||!confirm('Terminer la réunion ? Elle sera rangée dans les réunions terminées.'))return;setBusy(true);const current=sessions.find(s=>s.id===live.id),ended=new Date();const final=(current?.minutes||'')+'\n\nFIN DE RÉUNION : '+ended.toLocaleString('fr-FR');const {error}=await supabase.from('ca_meeting_sessions').update({status:'closed',ended_at:ended.toISOString(),minutes:final}).eq('id',live.id);if(!error)await supabase.from('records').update({status:'Terminé',notes:final,next:'Compte rendu disponible'}).eq('id',live.meeting_id);setBusy(false);if(error)return toast.error(error.message);toast.success('Réunion terminée.');await load();onChanged()}
 async function reopen(s:Session){if(!supabase||live)return toast.error('Une réunion est déjà en cours.');if(!confirm('Réouvrir cette réunion ?'))return;const {error}=await supabase.from('ca_meeting_sessions').update({status:'live',ended_at:null}).eq('id',s.id);if(!error)await supabase.from('records').update({status:'En cours'}).eq('id',s.meeting_id);if(error)return toast.error(error.message);setEditingClosed(null);toast.success('Réunion réouverte.');await load();onChanged()}
 async function cancel(s:Session){if(!supabase||!confirm('Annuler cette réunion ? Elle restera conservée comme réunion annulée.'))return;const {error}=await supabase.from('ca_meeting_sessions').update({status:'cancelled',ended_at:new Date().toISOString()}).eq('id',s.id);if(!error)await supabase.from('records').update({status:'Annulé',next:'Réunion annulée'}).eq('id',s.meeting_id);if(error)return toast.error(error.message);toast.success('Réunion annulée.');await load();onChanged()}
 const closed=sessions.filter(s=>s.status==='closed'),cancelled=sessions.filter(s=>s.status==='cancelled');
 return <section className="meeting-live">
 {!live?<div className="meeting-launch"><div><p className="eyebrow">MODE RÉUNION</p><h2>Lancer une réunion</h2><p className="muted">Au lancement, tous les membres actifs du CA sont ajoutés à la feuille de présence.</p></div>{canManage&&<div className="meeting-launch-actions"><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choisir une réunion préparée…</option>{meetings.filter(m=>m.status!=='Terminé'&&m.status!=='Annulé').map(m=><option key={m.id} value={m.id}>{m.title}{m.due?' · '+m.due:''}</option>)}</select><button className="primary" disabled={!selected||busy} onClick={start}><Play size={16}/> Lancer la réunion</button></div>}</div>:
 <div className="meeting-session"><div className="section-head"><div><p className="eyebrow">RÉUNION EN COURS</p><h2>{meeting?.title||'Réunion du CA'}</h2><small>Démarrée à {new Date(live.started_at).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</small></div></div><div className="rounded-xl border p-4 bg-white"><strong>Présences</strong><p className="muted">Clique sur chaque membre présent.</p><div className="flex flex-wrap gap-2 mt-3">{members.map(m=>{const checked=live.minutes.includes('☑ '+m.display_name);return <button type="button" key={m.user_id} disabled={!canManage} onClick={()=>togglePresent(m.display_name)} className={'px-3 py-2 rounded-lg border text-sm font-semibold '+(checked?'bg-green-100 border-green-500':'bg-white')}>{checked?'✓ ':'○ '}{m.display_name}</button>})}</div></div>{agendaItems.length>0&&<section className="meeting-agenda-live"><div className="section-head"><div><p className="eyebrow">ORDRE DU JOUR</p><h3>Points à traiter</h3><p className="muted">Survole un point pour voir ta note de préparation. Sur téléphone, touche le titre.</p></div></div><ol>{agendaItems.map((item,idx)=><li key={idx} className={item.note?'has-note':''} onMouseEnter={()=>item.note&&setOpenAgendaNote(idx)} onMouseLeave={()=>setOpenAgendaNote(null)}><button type="button" onClick={()=>item.note&&setOpenAgendaNote(openAgendaNote===idx?null:idx)}><span>{idx+1}</span><strong>{item.title}</strong>{item.note&&<StickyNote size={16}/>}</button>{item.note&&openAgendaNote===idx&&<aside className="agenda-postit"><small>NOTE PRIVÉE · COORDINATEUR</small><p>{item.note}</p></aside>}</li>)}</ol></section>}<div className="meeting-minutes-label"><strong>Compte rendu de la réunion</strong><span>Décisions, échanges et actions prises pendant le CA.</span></div><textarea className="meeting-minutes" rows={28} value={live.minutes} readOnly={!canManage} onChange={e=>save(live.id,e.target.value)}/>{canManage&&<div className="form-actions"><button className="primary" disabled={busy} onClick={finish}><Square size={16}/> Terminer la réunion</button></div>}<p className="muted">Les modifications sont enregistrées automatiquement.</p></div>}
 {closed.length>0&&<div className="meeting-archive"><div className="section-head"><div><p className="eyebrow">ARCHIVES</p><h2>Réunions terminées</h2><p className="muted">Le secrétariat peut corriger le compte rendu, ou réouvrir une réunion si nécessaire.</p></div></div>{closed.map(s=>{const m=meetings.find(x=>x.id===s.meeting_id);const edit=editingClosed===s.id;return <article key={s.id} className="meeting-session"><div className="section-head"><div><h3>{m?.title||'Réunion terminée'}</h3><small>{s.ended_at?'Terminée le '+new Date(s.ended_at).toLocaleString('fr-FR'):''}</small></div>{canManage&&<div className="form-actions"><button className="secondary" onClick={()=>setEditingClosed(edit?null:s.id)}>{edit?'Fermer le compte rendu':'Modifier le compte rendu'}</button><button className="secondary" onClick={()=>reopen(s)}><RotateCcw size={15}/> Réouvrir</button><button className="secondary" onClick={()=>cancel(s)}><XCircle size={15}/> Annuler</button></div>}</div>{edit&&<textarea className="meeting-minutes" rows={24} value={s.minutes} onChange={e=>save(s.id,e.target.value)}/>}</article>})}</div>}
 {cancelled.length>0&&<div className="meeting-archive"><h2>Réunions annulées</h2>{cancelled.map(s=>{const m=meetings.find(x=>x.id===s.meeting_id);return <article key={s.id} className="meeting-session"><strong>{m?.title||'Réunion annulée'}</strong>{canManage&&<button className="secondary" onClick={()=>reopen(s)}><RotateCcw size={15}/> Réouvrir</button>}</article>})}</div>}
 </section>
}