import {useEffect,useRef,useState} from 'react';
import {Play,RotateCcw,Square,XCircle,LockKeyhole,FileDown} from 'lucide-react';
import {supabase} from './lib/backend';
import {toast} from 'sonner';
import {jsPDF} from 'jspdf';
type Meeting={id:string;title:string;status:string;due?:string;notes:string;private_notes?:string;next:string};
type Session={id:string;meeting_id:string;status:string;started_at:string;ended_at?:string;minutes:string;ai_summary?:string};
type Member={user_id:string;display_name:string};
export default function MeetingLive({meetings,canManage,onChanged}:{meetings:Meeting[];canManage:boolean;onChanged:()=>void}){
 const [sessions,setSessions]=useState<Session[]>([]),[members,setMembers]=useState<Member[]>([]),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[editingClosed,setEditingClosed]=useState<string|null>(null),[privateTab,setPrivateTab]=useState(false),[privateDraft,setPrivateDraft]=useState(''),[privateSaving,setPrivateSaving]=useState(false),[mobilePdf,setMobilePdf]=useState<{url:string;name:string}|null>(null),[pdfBusy,setPdfBusy]=useState(false); const privateTimer=useRef<number|undefined>(undefined);
 async function load(){if(!supabase)return;const [{data:s},{data:m}]=await Promise.all([supabase.from('ca_meeting_sessions').select('*').order('started_at',{ascending:false}),supabase.from('ca_members').select('user_id,display_name').eq('active',true).order('display_name')]);setSessions((s||[]) as Session[]);setMembers((m||[]) as Member[])}
 useEffect(()=>{void load();const client=supabase;if(!client)return;let timer:number|undefined;const refresh=()=>window.setTimeout(()=>void load(),120);const channel=client.channel('meeting-live-sync').on('postgres_changes',{event:'*',schema:'public',table:'ca_meeting_sessions'},refresh).on('postgres_changes',{event:'UPDATE',schema:'public',table:'ca_proposals'},refresh).subscribe();timer=window.setInterval(()=>void load(),2000);return()=>{if(timer)window.clearInterval(timer);void client.removeChannel(channel)}},[]);
 const live=sessions.find(s=>s.status==='live'),meeting=meetings.find(m=>m.id===(live?.meeting_id||selected));
 useEffect(()=>{setPrivateDraft(meeting?.private_notes||'')},[meeting?.id,meeting?.private_notes]);
 async function persistPrivateNotes(value:string){if(!supabase||!meeting?.id||!canManage)return;setPrivateSaving(true);const {error}=await supabase.from('records').update({private_notes:value}).eq('id',meeting.id);setPrivateSaving(false);if(error)toast.error('Sauvegarde du pense-bête impossible.');else onChanged()}
 function changePrivateNotes(value:string){setPrivateDraft(value);if(privateTimer.current)window.clearTimeout(privateTimer.current);privateTimer.current=window.setTimeout(()=>void persistPrivateNotes(value),500)}
 useEffect(()=>()=>{if(privateTimer.current)window.clearTimeout(privateTimer.current)},[]);
 async function start(){if(!supabase||!selected)return;setBusy(true);const m=meetings.find(x=>x.id===selected);const attendance=members.length?members.map(x=>'☐ '+x.display_name).join('\n'):'À compléter';const header=['COMPTE RENDU — '+(m?.title||'Réunion du CA'),'Date : '+(m?.due?new Date(m.due+'T12:00:00').toLocaleDateString('fr-FR'):'à compléter'),'Début : '+new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}),'','PRÉSENCES — cocher les membres présents',attendance,'','ORDRE DU JOUR',(m?.notes||'À compléter').replace(/\\\\n/g,'\n'),'','NOTES, DÉCISIONS ET ACTIONS'].join('\n');const {error}=await supabase.from('ca_meeting_sessions').upsert({meeting_id:selected,status:'live',started_at:new Date().toISOString(),ended_at:null,minutes:header},{onConflict:'meeting_id'});setBusy(false);if(error)return toast.error(error.message);toast.success('Réunion lancée.');await load()}
 async function save(id:string,value:string){if(!supabase)return;setSessions(v=>v.map(s=>s.id===id?{...s,minutes:value}:s));const {error}=await supabase.from('ca_meeting_sessions').update({minutes:value}).eq('id',id);if(error)toast.error('Sauvegarde automatique impossible.')}
 async function togglePresent(name:string){if(!supabase||!live||!canManage)return;const unchecked='☐ '+name,checked='☑ '+name;const next=live.minutes.includes(checked)?live.minutes.replace(checked,unchecked):live.minutes.replace(unchecked,checked);await save(live.id,next);}
 async function finish(){if(!supabase||!live||!confirm('Terminer la réunion ? Elle sera rangée dans les réunions terminées.'))return;setBusy(true);const current=sessions.find(s=>s.id===live.id),ended=new Date();const final=(current?.minutes||'')+'\n\nFIN DE RÉUNION : '+ended.toLocaleString('fr-FR');const {error}=await supabase.from('ca_meeting_sessions').update({status:'closed',ended_at:ended.toISOString(),minutes:final}).eq('id',live.id);if(!error)await supabase.from('records').update({status:'Terminé',notes:final,next:'Compte rendu disponible'}).eq('id',live.meeting_id);setBusy(false);if(error)return toast.error(error.message);toast.success('Réunion terminée.');await load();onChanged()}
 async function reopen(s:Session){if(!supabase||live)return toast.error('Une réunion est déjà en cours.');if(!confirm('Réouvrir cette réunion ?'))return;const {error}=await supabase.from('ca_meeting_sessions').update({status:'live',ended_at:null}).eq('id',s.id);if(!error)await supabase.from('records').update({status:'En cours'}).eq('id',s.meeting_id);if(error)return toast.error(error.message);setEditingClosed(null);toast.success('Réunion réouverte.');await load();onChanged()}
 async function cancel(s:Session){if(!supabase||!confirm('Annuler cette réunion ? Elle restera conservée comme réunion annulée.'))return;const {error}=await supabase.from('ca_meeting_sessions').update({status:'cancelled',ended_at:new Date().toISOString()}).eq('id',s.id);if(!error)await supabase.from('records').update({status:'Annulé',next:'Réunion annulée'}).eq('id',s.meeting_id);if(error)return toast.error(error.message);toast.success('Réunion annulée.');await load();onChanged()}

 function safeFileName(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'')}
 function meetingDate(m?:Meeting){return m?.due?new Date(m.due+'T12:00:00').toLocaleDateString('fr-FR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}):'date à compléter'}
 async function logoPng(){try{const base=(import.meta.env.BASE_URL||'/').replace(/\/$/,'');const svg=await fetch(base+'/ffmc06-official-logo.svg').then(r=>r.text());const match=svg.match(/href="(data:image\/png;base64,[^"]+)"/);return match?.[1]||null}catch{return null}}
 async function exportPdf(kind:'agenda'|'minutes',m?:Meeting,s?:Session){
  if(!m)return toast.error('Réunion introuvable.');
  if(pdfBusy)return;setPdfBusy(true);toast.info('Génération du PDF…');
  try{
  const doc=new jsPDF({unit:'mm',format:'a4'}),isMinutes=kind==='minutes',date=meetingDate(m),source=isMinutes?(s?.minutes||''):(m.notes||'');
  const margin=18,pageW=210,pageH=297,contentW=174;let y=18;
  let logo:string|null=null;try{logo=await Promise.race([logoPng(),new Promise<null>(resolve=>window.setTimeout(()=>resolve(null),1500))])}catch{logo=null}if(logo){try{doc.addImage(logo,'PNG',margin,y,25,25)}catch{}}
  doc.setTextColor(20,20,20);doc.setFont('helvetica','bold');doc.setFontSize(10.5);doc.text('Fédération Française des Motards en Colère des Alpes-Maritimes',112,y+5,{align:'center'});
  doc.setFont('helvetica','normal');doc.setFontSize(7.5);doc.text('FFMC 06 – 11 rue de Rivoli – 06000 Nice · Tél. : 06.98.32.34.55',112,y+11,{align:'center'});doc.text('info@ffmc06.fr · www.ffmc06.fr/dotclear',112,y+15,{align:'center'});doc.text('Association régie par la loi de 1901, déclarée en préfecture des Alpes-Maritimes',112,y+20,{align:'center'});doc.text('sous le n° W062003812',112,y+24,{align:'center'});
  y=48;doc.setDrawColor(120);doc.line(margin,y,pageW-margin,y);y+=10;doc.setFont('helvetica','bold');doc.setFontSize(14);doc.text((isMinutes?'Compte rendu — ':'Ordre du jour — ')+m.title,pageW/2,y,{align:'center',maxWidth:contentW});y+=7;doc.setFont('helvetica','normal');doc.setFontSize(10);doc.text(date,pageW/2,y,{align:'center'});y+=11;
  const newPage=()=>{doc.addPage();y=20};
  const write=(text:string,bold=false,size=10,indent=0)=>{doc.setTextColor(20,20,20);doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(size);const lines=doc.splitTextToSize(text,contentW-indent);for(const line of lines){if(y>pageH-24)newPage();doc.text(line,margin+indent,y);y+=5.2}y+=1};
  if(isMinutes){
   const checked=[...source.matchAll(/^☑\s+(.+)$/gm)].map(x=>x[1].trim()),unchecked=[...source.matchAll(/^☐\s+(.+)$/gm)].map(x=>x[1].trim());
   write('Présents : '+(checked.join(', ')||'À compléter'),true,9.5);write('Absents : '+(unchecked.join(', ')||'À compléter'),true,9.5);y+=2;write('Compte rendu',true,11);
   const marker='NOTES, DÉCISIONS ET ACTIONS',idx=source.indexOf(marker);const detail=(idx>=0?source.slice(idx+marker.length):source).replace(/FIN DE RÉUNION\s*:[^\n]*/g,'').trim();
   for(const line of detail.split('\n')){const t=line.trim();if(!t){y+=2;continue}const heading=/^[A-ZÀ-ÖØ-Ý0-9 ,’'\-–—]+$/.test(t)&&t.length<100;write(t,heading,heading?10.5:9.5)}
   if(y>pageH-42)newPage();y+=14;doc.setFont('helvetica','normal');doc.setFontSize(9.5);doc.text('Le coordinateur :',margin,y);doc.text('Le secrétaire :',125,y);y+=6;doc.setFont('helvetica','bold');doc.text('Antoine Fabre',margin,y);doc.setFont('helvetica','normal');doc.text('________________________',125,y);
  }else{
   write('Ordre du jour',true,11);const items=source.replace(/\\\\n/g,'\n').split('\n').map(x=>x.trim()).filter(Boolean);for(const raw of items){write('• '+raw.replace(/^[-•]\s*/,''),false,10,3)}
  }
  const pages=doc.getNumberOfPages();for(let i=1;i<=pages;i++){doc.setPage(i);doc.setFont('helvetica','normal');doc.setFontSize(7.5);doc.setTextColor(100);doc.text('FFMC 06 · '+(isMinutes?'Compte rendu':'Ordre du jour'),margin,288);doc.text(String(i)+' / '+String(pages),pageW-margin,288,{align:'right'})}
  const filename='FFMC06_'+(isMinutes?'Compte-rendu':'Ordre-du-jour')+'_'+safeFileName(m.title)+(m.due?'_'+m.due:'')+'.pdf';
  const mobile=/iPhone|iPad|iPod|Android/i.test(navigator.userAgent)||window.matchMedia('(max-width: 700px)').matches;
  if(mobile){
   const blob=doc.output('blob'),url=URL.createObjectURL(blob);setMobilePdf(prev=>{if(prev?.url)URL.revokeObjectURL(prev.url);return{url,name:filename}});toast.success('PDF prêt : touche « Ouvrir le PDF ».');
  }else{doc.save(filename);toast.success('PDF téléchargé.');}
  }catch(error){console.error('PDF generation failed',error);toast.error('Impossible de générer le PDF. Réessaie après avoir rechargé la page.');}
  finally{setPdfBusy(false)}
 }

  const closed=sessions.filter(s=>s.status==='closed'),cancelled=sessions.filter(s=>s.status==='cancelled');
 return <section className="meeting-live">{mobilePdf&&<div className="mobile-pdf-ready" role="dialog" aria-modal="true"><div className="mobile-pdf-card"><FileDown size={30}/><h3>PDF prêt</h3><p>{mobilePdf.name}</p><a className="primary mobile-pdf-open" href={mobilePdf.url} target="_blank" rel="noopener">Ouvrir le PDF</a><a className="secondary mobile-pdf-download" href={mobilePdf.url} download={mobilePdf.name}>Enregistrer le PDF</a><button type="button" className="ghost" onClick={()=>{URL.revokeObjectURL(mobilePdf.url);setMobilePdf(null)}}>Fermer</button></div></div>}
 {!live?<div className="meeting-launch"><div><p className="eyebrow">MODE RÉUNION</p><h2>Lancer une réunion</h2><p className="muted">Au lancement, tous les membres actifs du CA sont ajoutés à la feuille de présence.</p></div>{canManage&&<div className="meeting-launch-actions"><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choisir une réunion préparée…</option>{meetings.filter(m=>m.status!=='Terminé'&&m.status!=='Annulé').map(m=><option key={m.id} value={m.id}>{m.title}{m.due?' · '+m.due:''}</option>)}</select><button className="secondary" disabled={!selected} onClick={()=>exportPdf('agenda',meetings.find(m=>m.id===selected))}><FileDown size={16}/> {pdfBusy?'Génération…':'PDF ordre du jour'}</button><button className="primary" disabled={!selected||busy} onClick={start}><Play size={16}/> Lancer la réunion</button></div>}</div>:
 <div className="meeting-session"><div className="section-head"><div><p className="eyebrow">RÉUNION EN COURS</p><h2>{meeting?.title||'Réunion du CA'}</h2><small>Démarrée à {new Date(live.started_at).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</small></div><div className="form-actions"><button className="secondary" onClick={()=>exportPdf('agenda',meeting)}><FileDown size={15}/> {pdfBusy?'Génération…':'Ordre du jour PDF'}</button><button className="secondary" onClick={()=>exportPdf('minutes',meeting,live)}><FileDown size={15}/> {pdfBusy?'Génération…':'Compte rendu PDF'}</button></div></div><div className="rounded-xl border p-4 bg-white"><strong>Présences</strong><p className="muted">Clique sur chaque membre présent.</p><div className="flex flex-wrap gap-2 mt-3">{members.map(m=>{const checked=live.minutes.includes('☑ '+m.display_name);return <button type="button" key={m.user_id} disabled={!canManage} onClick={()=>togglePresent(m.display_name)} className={'px-3 py-2 rounded-lg border text-sm font-semibold '+(checked?'bg-green-100 border-green-500':'bg-white')}>{checked?'✓ ':'○ '}{m.display_name}</button>})}</div></div><div className="meeting-work-tabs"><button type="button" className={!privateTab?'active':''} onClick={()=>setPrivateTab(false)}>Compte rendu</button><button type="button" className={privateTab?'active private':''} onClick={()=>setPrivateTab(true)}><LockKeyhole size={15}/> Notes privées</button></div>{privateTab?<section className="meeting-private-panel"><div><p className="eyebrow">PENSE-BÊTE PERSONNEL</p><h3>Notes privées</h3><p className="muted">Ces notes servent à préparer et conduire la réunion. Elles ne font pas partie du compte rendu.</p></div><textarea rows={18} value={privateDraft} readOnly={!canManage} onChange={e=>changePrivateNotes(e.target.value)} onBlur={e=>{if(privateTimer.current)window.clearTimeout(privateTimer.current);void persistPrivateNotes(e.target.value)}} placeholder="Écris ici ton pense-bête pour la réunion…"/><small className="private-save-state">{privateSaving?'Enregistrement…':'✓ Sauvegarde automatique'}</small></section>:<><div className="meeting-minutes-label"><strong>Compte rendu de la réunion</strong><span>Décisions, échanges et actions prises pendant le CA.</span></div><textarea className="meeting-minutes" rows={28} value={live.minutes} readOnly={!canManage} onChange={e=>save(live.id,e.target.value)}/></>}{canManage&&<div className="form-actions"><button className="primary" disabled={busy} onClick={finish}><Square size={16}/> Terminer la réunion</button></div>}<p className="muted">Les modifications sont enregistrées automatiquement.</p></div>}
 {closed.length>0&&<div className="meeting-archive"><div className="section-head"><div><p className="eyebrow">ARCHIVES</p><h2>Réunions terminées</h2><p className="muted">Le secrétariat peut corriger le compte rendu, ou réouvrir une réunion si nécessaire.</p></div></div>{closed.map(s=>{const m=meetings.find(x=>x.id===s.meeting_id);const edit=editingClosed===s.id;return <article key={s.id} className="meeting-session"><div className="section-head"><div><h3>{m?.title||'Réunion terminée'}</h3><small>{s.ended_at?'Terminée le '+new Date(s.ended_at).toLocaleString('fr-FR'):''}</small></div>{canManage&&<div className="form-actions"><button className="secondary" onClick={()=>exportPdf('minutes',m,s)}><FileDown size={15}/> PDF</button><button className="secondary" onClick={()=>setEditingClosed(edit?null:s.id)}>{edit?'Fermer le compte rendu':'Modifier le compte rendu'}</button><button className="secondary" onClick={()=>reopen(s)}><RotateCcw size={15}/> Réouvrir</button><button className="secondary" onClick={()=>cancel(s)}><XCircle size={15}/> Annuler</button></div>}</div>{edit&&<textarea className="meeting-minutes" rows={24} value={s.minutes} onChange={e=>save(s.id,e.target.value)}/>}</article>})}</div>}
 {cancelled.length>0&&<div className="meeting-archive"><h2>Réunions annulées</h2>{cancelled.map(s=>{const m=meetings.find(x=>x.id===s.meeting_id);return <article key={s.id} className="meeting-session"><strong>{m?.title||'Réunion annulée'}</strong>{canManage&&<button className="secondary" onClick={()=>reopen(s)}><RotateCcw size={15}/> Réouvrir</button>}</article>})}</div>}
 </section>
}