import {useEffect,useState} from 'react';
import {UserPlus,Users,RefreshCw} from 'lucide-react';
import {supabase} from './lib/backend';
import {toast} from 'sonner';
type M={user_id:string;display_name:string;email:string;position:string;role:string;active:boolean};
export default function MemberAdmin(){const [items,setItems]=useState<M[]>([]),[busy,setBusy]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState(''),[position,setPosition]=useState('Membre du CA'),[role,setRole]=useState('membre');
async function call(body:any){const {data,error}=await supabase!.functions.invoke('member-admin',{body});if(error){const response=(error as any).context;let message=error.message;if(response){try{const payload=await response.clone().json();message=payload?.error||message}catch{}}throw Error(message)}if(data?.error)throw Error(data.error);return data;}
async function load(){setBusy(true);try{setItems((await call({action:'list'})).data||[])}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}} useEffect(()=>{void load()},[]);
async function invite(e:React.FormEvent){e.preventDefault();setBusy(true);try{await call({action:'invite',name,email,position,role});toast.success('Invitation envoyée');setName('');setEmail('');await load()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
async function update(m:M,patch:Partial<M>){setBusy(true);try{await call({action:'update',user_id:m.user_id,...patch});toast.success('Membre mis à jour');await load()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
return <section className="member-admin"><div className="member-admin-head"><div><p className="eyebrow">CONSEIL D’ADMINISTRATION</p><h2>Gestion des membres</h2><p className="subtitle">Inviter un membre, définir sa fonction et gérer son accès à l’espace CA.</p></div><button className="secondary" onClick={load} disabled={busy}><RefreshCw size={15}/>Actualiser</button></div><form className="member-invite" onSubmit={invite}><div className="invite-intro"><span className="invite-icon"><UserPlus size={22}/></span><div><h3>Inviter au CA</h3><p>La personne recevra un lien sécurisé pour créer son accès.</p></div></div><div className="invite-main"><label className="invite-name"><span>Nom et prénom</span><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Ex. Jean Dupont"/></label><label className="invite-email"><span>Adresse e-mail</span><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="jean@exemple.fr"/></label></div><div className="invite-options"><label><span>Fonction au CA</span><input value={position} onChange={e=>setPosition(e.target.value)} placeholder="Membre du CA"/></label><label><span>Accès</span><select value={role} onChange={e=>setRole(e.target.value)}><option value="membre">Membre · consultation & participation</option><option value="coordinateur">Coordinateur · gestion complète</option></select></label><button className="primary invite-submit" disabled={busy}><UserPlus size={16}/>{busy?'Envoi…':'Envoyer l’invitation'}</button></div><p className="invite-footnote">Aucun mot de passe à transmettre : le membre définit le sien depuis l’e-mail reçu.</p></form><div className="member-list"><h3><Users size={18}/> Membres ({items.length})</h3>{items.map(m=><article className={'member-admin-card '+(!m.active?'inactive':'')} key={m.user_id}><div><strong>{m.display_name||m.email||'Membre'}</strong><span>{m.email}</span><small>{m.position}</small></div><label>Fonction<input defaultValue={m.position} onBlur={e=>{if(e.target.value!==m.position)void update(m,{position:e.target.value})}}/></label><label>Accès<select value={m.role} onChange={e=>void update(m,{role:e.target.value})}><option value="membre">Membre</option><option value="coordinateur">Coordinateur</option></select></label><button type="button" className="secondary" disabled={busy} onClick={()=>void update(m,{active:!m.active})}>{m.active?'Désactiver':'Réactiver'}</button></article>)}</div></section>}
