import {useEffect,useMemo,useState} from 'react';
import {Bell,CalendarDays,FileText,Home,Lightbulb,Newspaper,Plus,RefreshCw,Users} from 'lucide-react';
import {supabase} from './lib/backend';
import SharedMail from './SharedMail';
import {toast,Toaster} from 'sonner';

type Pub={id:string;title:string;body:string;published:boolean;category?:string;event_date?:string;created_at?:string};
type News={id:string;title:string;body:string;topic:string;news_type:string;published_at?:string;event_date?:string;kind?:string};
type Idea={id:string;title:string;body:string;status:string;created_at:string};
const tabs=[['Accueil',Home],['Actualités',Newspaper],['Réunions',Users],['Agenda',CalendarDays],['Idées',Lightbulb],['Publications',FileText]] as const;
export default function MemberPortal({preview=false}:{preview?:boolean}){
 const [view,setView]=useState('Accueil'),[pubs,setPubs]=useState<Pub[]>([]),[news,setNews]=useState<News[]>([]),[ideas,setIdeas]=useState<Idea[]>([]),[loading,setLoading]=useState(true),[ideaOpen,setIdeaOpen]=useState(false),[postOpen,setPostOpen]=useState(false),[title,setTitle]=useState(''),[body,setBody]=useState('');
 async function refresh(){if(!supabase)return;setLoading(true);const [p,n,i]=await Promise.all([supabase.from('ca_publications').select('id,title,body,published,category,event_date,created_at').eq('published',true).order('created_at',{ascending:false}),supabase.from('ca_news_items').select('id,title,body,topic,news_type,published_at,event_date,kind').order('published_at',{ascending:false}).limit(500),supabase.from('ca_ideas').select('id,title,body,status,created_at').order('created_at',{ascending:false})]);setPubs((p.data||[]) as Pub[]);setNews((n.data||[]) as News[]);setIdeas((i.data||[]) as Idea[]);setLoading(false);}
 useEffect(()=>{void refresh();const client=supabase;if(!client)return;const channel=client.channel('member-portal-live').on('postgres_changes',{event:'*',schema:'public',table:'ca_news_items'},()=>void refresh()).on('postgres_changes',{event:'*',schema:'public',table:'ca_publications'},()=>void refresh()).on('postgres_changes',{event:'*',schema:'public',table:'ca_ideas'},()=>void refresh()).subscribe();return()=>{void client.removeChannel(channel);};},[]);
 const meetings=useMemo(()=>news.filter(n=>n.news_type==='Compte rendu CA'||/compte rendu|réunion|ca\b/i.test(n.topic+' '+n.title)),[news]);
 const externalIdeas=useMemo(()=>news.filter(n=>n.kind==='initiative_ffmc'),[news]);
 const events=useMemo(()=>[...pubs.filter(p=>p.event_date).map(p=>({date:p.event_date!,title:p.title,type:p.category||'Événement'})),...news.filter(n=>n.event_date).map(n=>({date:n.event_date!,title:n.title,type:n.news_type||'Actualité'}))].sort((a,b)=>a.date.localeCompare(b.date)),[pubs,news]);
 async function submitIdea(e:React.FormEvent){e.preventDefault();if(!supabase)return;const {error}=await supabase.from('ca_ideas').insert({title:title.trim(),body:body.trim()});if(error)return toast.error('Impossible d’ajouter l’idée.');setTitle('');setBody('');setIdeaOpen(false);toast.success('Idée proposée au CA.');await refresh();}
 async function submitPost(e:React.FormEvent){e.preventDefault();if(!supabase)return;const {error}=await supabase.from('ca_publications').insert({title:title.trim(),body:body.trim(),published:false,category:'Proposition de publication'});if(error)return toast.error('Impossible d’envoyer la publication.');setTitle('');setBody('');setPostOpen(false);toast.success('Publication envoyée au coordinateur pour validation.');}
 const Card=({n}:{n:News})=><article className="member-card"><span className="member-chip">{n.news_type||n.topic}</span><h3>{n.title}</h3><p>{n.body}</p>{n.published_at&&<small>{new Date(n.published_at).toLocaleDateString('fr-FR')}</small>}</article>;
 return <div className="ca-portal">{preview&&<div className="preview-banner">Aperçu de l’espace membre du CA</div>}<header className="ca-head"><div className="member-brand"><span>06</span><strong>FFMC · ESPACE CA</strong></div><button className="secondary" onClick={refresh}><RefreshCw size={15}/> Actualiser</button></header><nav className="ca-tabs">{tabs.map(([t,I])=><button key={t} className={view===t?'active':''} onClick={()=>setView(t)}><I size={17}/>{t}</button>)}</nav><main className="ca-content">{loading?<p className="muted">Chargement de l’espace CA…</p>:<>
 {view==='Accueil'&&<><div className="ca-welcome"><div><p className="eyebrow">TABLEAU DE BORD DU CA</p><h1>Bonjour 👋</h1><p>Les informations utiles au conseil d’administration, sans le courrier privé du coordinateur.</p></div><Bell size={34}/></div><div className="ca-metrics"><button onClick={()=>setView('Actualités')}><strong>{news.length+pubs.length}</strong><span>informations</span></button><button onClick={()=>setView('Réunions')}><strong>{meetings.length}</strong><span>comptes rendus</span></button><button onClick={()=>setView('Agenda')}><strong>{events.length}</strong><span>dates à l’agenda</span></button><button onClick={()=>setView('Idées')}><strong>{ideas.length+externalIdeas.length}</strong><span>idées à regarder</span></button></div><h2 className="below">À voir par le CA</h2><div className="member-grid">{news.slice(0,4).map(n=><Card key={n.id} n={n}/>)}</div></>}
 {view==='Actualités'&&<><div className="ca-title"><div><p className="eyebrow">INFORMATIONS & NEWS</p><h1>Actualités du CA et de la FFMC 06</h1></div></div><div className="member-grid">{news.map(n=><Card key={n.id} n={n}/>)}</div><div className="below"><SharedMail/></div></>}
 {view==='Réunions'&&<><div className="ca-title"><p className="eyebrow">RÉUNIONS DU CA</p><h1>Comptes rendus et décisions</h1><p className="subtitle">Les comptes rendus PDF validés et les décisions partagées apparaissent ici.</p></div><div className="member-grid">{meetings.map(n=><Card key={n.id} n={n}/>)}</div></>}
 {view==='Agenda'&&<><div className="ca-title"><p className="eyebrow">AGENDA</p><h1>Prochaines dates</h1></div><div className="ca-agenda">{events.length?events.map((e,i)=><article key={i}><time>{new Date(e.date+'T12:00:00').toLocaleDateString('fr-FR',{day:'2-digit',month:'short',year:'numeric'})}</time><div><strong>{e.title}</strong><small>{e.type}</small></div></article>):<p className="muted">Aucune date partagée pour le moment.</p>}</div></>}
 {view==='Idées'&&<><div className="ca-title ca-row"><div><p className="eyebrow">BOÎTE À IDÉES</p><h1>Proposer et découvrir</h1></div><button className="primary" onClick={()=>{setTitle('');setBody('');setIdeaOpen(true)}}><Plus size={16}/> Ajouter une idée</button></div>{externalIdeas.length>0&&<><h2>Idées repérées dans les autres antennes</h2><div className="member-grid">{externalIdeas.map(n=><Card key={n.id} n={n}/>)}</div></>}<h2 className="below">Idées proposées par le CA</h2><div className="member-grid">{ideas.map(i=><article className="member-card" key={i.id}><span className="member-chip">{i.status}</span><h3>{i.title}</h3><p>{i.body}</p></article>)}</div></>}
 {view==='Publications'&&<><div className="ca-title ca-row"><div><p className="eyebrow">PUBLICATIONS</p><h1>Informations publiées au CA</h1></div><button className="primary" onClick={()=>{setTitle('');setBody('');setPostOpen(true)}}><Plus size={16}/> Proposer une publication</button></div><p className="subtitle">Une proposition d’un membre est envoyée au coordinateur en brouillon avant publication.</p><div className="publications">{pubs.map(p=><article className="publication" key={p.id}><span className="member-chip">{p.category||'Publication'}</span><h2>{p.title}</h2><div className="publication-body">{p.body}</div></article>)}</div></>}
 </>}</main>{(ideaOpen||postOpen)&&<div className="ca-modal" onMouseDown={()=>{setIdeaOpen(false);setPostOpen(false)}}><form onMouseDown={e=>e.stopPropagation()} onSubmit={ideaOpen?submitIdea:submitPost}><h2>{ideaOpen?'Nouvelle idée':'Proposer une publication'}</h2><p>{postOpen?'Elle sera relue par le coordinateur avant d’être visible par le CA.':'Décrivez simplement votre proposition.'}</p><label>Titre<input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Description<textarea required rows={7} maxLength={10000} value={body} onChange={e=>setBody(e.target.value)}/></label><div className="form-actions"><button type="button" className="secondary" onClick={()=>{setIdeaOpen(false);setPostOpen(false)}}>Annuler</button><button className="primary">Envoyer</button></div></form></div>}<Toaster richColors position="bottom-right"/></div>;
}