import {useEffect,useMemo,useState} from 'react';
import {Bell,CalendarDays,FileText,Home,Lightbulb,Newspaper,Plus,RefreshCw,Users,Vote,BellRing,FolderOpen,Euro,ShieldCheck} from 'lucide-react';
import {supabase} from './lib/backend';
import SharedMail from './SharedMail';
import MotoNews from './MotoNews';
import {toast,Toaster} from 'sonner';
import VotesBoard,{NotificationsPanel} from './VotesBoard';
import VoltigeursPortal from './VoltigeursPortal';
import SecretariatPortal from './SecretariatPortal';
import DocumentsPortal from './DocumentsPortal';
import TreasuryPortal from './TreasuryPortal';
import SecurityPortal from './SecurityPortal';
import RMCPortal from './RMCPortal';
import MeetingLive from './MeetingLive';

type Pub={id:string;title:string;body:string;published:boolean;category?:string;event_date?:string;created_at?:string};
type Source={label:string;url:string;date?:string};
type News={id:string;title:string;body:string;topic:string;news_type:string;published_at?:string;event_date?:string;kind?:string;source_refs?:Source[]};
const decode=(value:string)=>{const el=document.createElement('textarea');el.innerHTML=value;return el.value.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()};
const safeUrl=(value:string)=>{try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:undefined}catch{return undefined}};
type Idea={id:string;title:string;body:string;status:string;created_at:string;author_name?:string};
type Meeting={id:string;title:string;status:string;owner:string;due?:string;notes:string;next:string;kind?:string};
const baseTabs=[['Accueil',Home],['Actualités',Newspaper],['Partages du coordinateur',FileText],['Réunions',Users],['Agenda',CalendarDays],['Idées',Lightbulb],['Votes',Vote],['Notifications',BellRing]] as const;
export default function MemberPortal({preview=false,permissions=[],role='membre'}:{preview?:boolean;permissions?:string[];role?:string}){
 const has=(p:string)=>permissions.includes(p)||role==='coordinateur';
 const tabs=[...baseTabs.filter(([t])=>t==='Accueil'||(['Actualités'].includes(t)&&has('actualites'))||(['Votes','Notifications'].includes(t)&&(has('votes')||has('secretariat')))||(['Partages du coordinateur','Réunions','Agenda','Idées'].includes(t)&&has('ca'))),...(has('secretariat')?[['Secrétariat',FileText] as const]:[]),...((has('ca')||has('secretariat')||has('administration'))?[['Documents',FolderOpen] as const]:[]),...(has('tresorerie')?[['Trésorerie',Euro] as const]:[]),...(has('voltigeurs')?[['Voltigeurs',Users] as const]:[]),...(has('ca')?[['RMC',FolderOpen] as const]:[]),['Sécurité',ShieldCheck] as const];
 const [calendarMonth,setCalendarMonth]=useState(()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1)}),[view,setView]=useState('Accueil'),[pubs,setPubs]=useState<Pub[]>([]),[news,setNews]=useState<News[]>([]),[ideas,setIdeas]=useState<Idea[]>([]),[caMeetings,setCaMeetings]=useState<Meeting[]>([]),[caRecords,setCaRecords]=useState<Meeting[]>([]),[loading,setLoading]=useState(true),[ideaOpen,setIdeaOpen]=useState(false),[postOpen,setPostOpen]=useState(false),[title,setTitle]=useState(''),[body,setBody]=useState('');
 async function refresh(){if(!supabase)return;setLoading(true);const [p,n,i,r]=await Promise.all([supabase.from('ca_publications').select('id,title,body,published,category,event_date,created_at').eq('published',true).order('created_at',{ascending:false}),supabase.from('ca_news_items').select('id,title,body,topic,news_type,published_at,event_date,kind,source_refs').order('published_at',{ascending:false}).limit(500),supabase.from('ca_ideas').select('id,title,body,status,created_at,author_name').order('created_at',{ascending:false}),supabase.from('records').select('id,title,status,owner,due,notes,next,kind').in('kind',['Réunion','Action']).order('due',{ascending:true})]);setPubs((p.data||[]) as Pub[]);setNews((n.data||[]) as News[]);setIdeas((i.data||[]) as Idea[]);const records=(r.data||[]) as Meeting[];setCaRecords(records);setCaMeetings(records.filter(x=>x.kind==='Réunion'));setLoading(false);}
 useEffect(()=>{void refresh();const client=supabase;if(!client)return;const channel=client.channel('member-portal-live').on('postgres_changes',{event:'*',schema:'public',table:'ca_news_items'},()=>void refresh()).on('postgres_changes',{event:'*',schema:'public',table:'ca_publications'},()=>void refresh()).on('postgres_changes',{event:'*',schema:'public',table:'ca_ideas'},()=>void refresh()).on('postgres_changes',{event:'*',schema:'public',table:'records'},()=>void refresh()).subscribe();return()=>{void client.removeChannel(channel);};},[]);
 const meetings=useMemo(()=>news.filter(n=>{const s=(n.news_type+' '+n.topic+' '+decode(n.title)+' '+decode(n.body)).toLowerCase();const isReport=n.news_type==='Compte rendu CA'||/compte.?rendu|\bcr\b/.test(s);const isUseful=/bureau national|\bbn\b|ffmc 06|antenne 06|conseil d.administration|\bca\b|assises/.test(s)||n.news_type==='Compte rendu CA';return isReport&&isUseful&&!/démission|demission/.test(s)}),[news]);
 const externalIdeas=useMemo(()=>news.filter(n=>n.kind==='initiative_ffmc'),[news]);
 const events=useMemo(()=>[...caRecords.filter(r=>r.due).map(r=>({date:r.due!,title:r.title,type:r.kind||'Action'})),...pubs.filter(p=>p.event_date).map(p=>({date:p.event_date!,title:p.title,type:p.category||'Action'})),...news.filter(n=>n.event_date).map(n=>({date:n.event_date!,title:n.title,type:/réunion|compte rendu|ca\b/i.test(n.news_type+' '+n.topic+' '+n.title)?'Réunion':n.news_type||'Action'}))].sort((a,b)=>a.date.localeCompare(b.date)),[caMeetings,pubs,news]);
 const calendar=useMemo(()=>{const y=calendarMonth.getFullYear(),m=calendarMonth.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),offset=(first.getDay()+6)%7;return Array.from({length:Math.ceil((offset+days)/7)*7},(_,i)=>{const day=i-offset+1;if(day<1||day>days)return null;const date=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;return {day,date,events:events.filter(e=>e.date===date)}})},[calendarMonth,events]);
 async function submitIdea(e:React.FormEvent){e.preventDefault();if(!supabase)return;const {error}=await supabase.from('ca_ideas').insert({title:title.trim(),body:body.trim()});if(error)return toast.error('Impossible d’ajouter l’idée.');setTitle('');setBody('');setIdeaOpen(false);toast.success('Idée proposée au CA.');await refresh();}
 async function submitPost(e:React.FormEvent){e.preventDefault();if(!supabase)return;const {error}=await supabase.from('ca_publications').insert({title:title.trim(),body:body.trim(),published:false,category:'Proposition de publication'});if(error)return toast.error('Impossible d’envoyer la publication.');setTitle('');setBody('');setPostOpen(false);toast.success('Publication envoyée au coordinateur pour validation.');}
 const Card=({n}:{n:News})=><article className="member-card"><span className="member-chip">{n.news_type||n.topic}</span><h3>{decode(n.title)}</h3><p>{decode(n.body)}</p>{n.published_at&&<small>{new Date(n.published_at).toLocaleDateString('fr-FR')}</small>}{n.source_refs&&n.source_refs.length>0&&<details className="member-sources"><summary>Sources ({n.source_refs.length})</summary><ul>{n.source_refs.map((s,i)=>{const url=safeUrl(s.url);return <li key={i}>{url?<a href={url} target="_blank" rel="noreferrer">{decode(s.label)} ↗</a>:decode(s.label)}{s.date&&<small> · {s.date}</small>}</li>})}</ul></details>}</article>;
 return <div className="ca-portal">{preview&&<div className="preview-banner">Aperçu de l’espace membre du CA</div>}<header className="ca-head"><div className="member-brand"><span>06</span><strong>FFMC · ESPACE CA</strong></div><button className="secondary" onClick={refresh}><RefreshCw size={15}/> Actualiser</button></header><nav className="ca-tabs">{tabs.map(([t,I])=><button key={t} className={view===t?'active':''} onClick={()=>setView(t)}><I size={17}/>{t}</button>)}</nav><main className="ca-content">{loading?<p className="muted">Chargement de l’espace CA…</p>:<>
 {view==='Accueil'&&<><div className="ca-welcome"><div><p className="eyebrow">TABLEAU DE BORD DU CA</p><h1>Bonjour 👋</h1><p>Les dernières actualités moto et politiques utiles au conseil d’administration.</p></div><Bell size={34}/></div><div className="ca-home-news"><MotoNews readOnly onPrepareShare={()=>{}} onPrepareRecord={()=>{}}/></div></>}
 {view==='Actualités'&&<MotoNews readOnly onPrepareShare={()=>{}} onPrepareRecord={()=>{}}/>}
 {view==='Partages du coordinateur'&&<SharedMail/>}
 {view==='Réunions'&&<><MeetingLive meetings={caMeetings} canManage={has('secretariat')} onChanged={refresh}/><div className="ca-title"><p className="eyebrow">RÉUNIONS DU CA</p><h1>Comptes rendus et décisions</h1><p className="subtitle">Les comptes rendus de nos réunions FFMC 06 / CA, ceux ajoutés sur le site, ainsi que les comptes rendus utiles du Bureau national (BN) et des Assises.</p></div><h2>Prochaines réunions</h2><div className="member-grid">{caMeetings.filter(r=>r.status!=='Terminé'&&r.status!=='Annulé').map(r=><article className="member-card" key={r.id}><span className="member-chip">{r.status}</span><h3>{r.title}</h3>{r.due&&<small>{new Date(r.due+'T12:00:00').toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</small>}{r.notes&&<p className="whitespace-pre-wrap">{r.notes.replaceAll('\\\\n','\n')}</p>}{r.next&&<p><strong>Prochaine étape :</strong> {r.next}</p>}</article>)}</div><h2 className="below">Comptes rendus et décisions</h2><div className="member-grid">{meetings.map(n=><Card key={n.id} n={n}/>)}</div></>}
 {view==='Agenda'&&<><div className="ca-title ca-row"><div><p className="eyebrow">AGENDA DU CA</p><h1>Actions & réunions</h1></div><div className="calendar-nav"><button className="secondary" onClick={()=>setCalendarMonth(d=>new Date(d.getFullYear(),d.getMonth()-1,1))}>‹</button><strong>{calendarMonth.toLocaleDateString('fr-FR',{month:'long',year:'numeric'})}</strong><button className="secondary" onClick={()=>setCalendarMonth(d=>new Date(d.getFullYear(),d.getMonth()+1,1))}>›</button></div></div><div className="ca-calendar"><div className="calendar-weekdays">{['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'].map(d=><strong key={d}>{d}</strong>)}</div><div className="calendar-grid">{calendar.map((cell,i)=><div key={i} className={'calendar-day '+(!cell?'calendar-empty':'')}>{cell&&<><span>{cell.day}</span>{cell.events.map((e,j)=><div key={j} className={'calendar-event '+(/réunion/i.test(e.type)?'meeting':'action')} title={e.title}><small>{e.type}</small><b>{e.title}</b></div>)}</>}</div>)}</div></div>{!events.length&&<p className="muted">Les actions et réunions datées apparaîtront automatiquement dans le calendrier.</p>}</>}
 {view==='Idées'&&<><div className="ca-title ca-row"><div><p className="eyebrow">BOÎTE À IDÉES</p><h1>Proposer et découvrir</h1></div><button className="primary" onClick={()=>{setTitle('');setBody('');setIdeaOpen(true)}}><Plus size={16}/> Ajouter une idée</button></div>{externalIdeas.length>0&&<><h2>Idées repérées dans les autres antennes</h2><div className="member-grid">{externalIdeas.map(n=><Card key={n.id} n={n}/>)}</div></>}<h2 className="below">Idées proposées par le CA</h2><div className="member-grid">{ideas.map(i=><article className="member-card" key={i.id}><span className="member-chip">{i.status}</span><h3>{i.title}</h3><p>{i.body}</p><small className="idea-author">Proposée par <strong>{i.author_name||'Membre du CA'}</strong>{i.created_at&&<> · {new Date(i.created_at).toLocaleDateString('fr-FR')}</>}</small></article>)}</div></>}
 {view==='Votes'&&<VotesBoard/>}\n {view==='Notifications'&&<NotificationsPanel onNavigate={(tab)=>setView(tab==='votes'?'Votes':'Notifications')}/>}\n {view==='Secrétariat'&&has('secretariat')&&<SecretariatPortal/>}
 {view==='Documents'&&(has('ca')||has('secretariat')||has('administration'))&&<DocumentsPortal canWrite={has('secretariat')||has('administration')} canSeeTreasury={has('tresorerie')}/>} 
 {view==='Trésorerie'&&has('tresorerie')&&<TreasuryPortal/>}
 {view==='RMC'&&has('ca')&&<RMCPortal canEdit={has('rmc')||role==='coordinateur'}/>}
 {view==='Sécurité'&&<SecurityPortal/>}
 {view==='Voltigeurs'&&has('voltigeurs')&&<VoltigeursPortal role={role}/>}

 </>}</main>{(ideaOpen||postOpen)&&<div className="ca-modal" onMouseDown={()=>{setIdeaOpen(false);setPostOpen(false)}}><form onMouseDown={e=>e.stopPropagation()} onSubmit={ideaOpen?submitIdea:submitPost}><h2>{ideaOpen?'Nouvelle idée':'Proposer une publication'}</h2><p>{postOpen?'Elle sera relue par le coordinateur avant d’être visible par le CA.':'Décrivez simplement votre proposition.'}</p><label>Titre<input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Description<textarea required rows={7} maxLength={10000} value={body} onChange={e=>setBody(e.target.value)}/></label><div className="form-actions"><button type="button" className="secondary" onClick={()=>{setIdeaOpen(false);setPostOpen(false)}}>Annuler</button><button className="primary">Envoyer</button></div></form></div>}<Toaster richColors position="bottom-right"/></div>;
}