import {useEffect,useMemo,useState} from 'react';
import {Bell,CalendarDays,FileText,Home,Lightbulb,Newspaper,Plus,RefreshCw,Users} from 'lucide-react';
import {supabase} from './lib/backend';
import SharedMail from './SharedMail';
import {toast,Toaster} from 'sonner';

type Pub={id:string;title:string;body:string;published:boolean;category?:string;event_date?:string;created_at?:string};
type Source={label:string;url:string;date?:string};
type News={id:string;title:string;body:string;topic:string;news_type:string;published_at?:string;event_date?:string;kind?:string;source_refs?:Source[]};
const decode=(value:string)=>{const el=document.createElement('textarea');el.innerHTML=value;return el.value.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()};
const safeUrl=(value:string)=>{try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:undefined}catch{return undefined}};
type Idea={id:string;title:string;body:string;status:string;created_at:string};
const tabs=[['Accueil',Home],['Actualités',Newspaper],['Réunions',Users],['Agenda',CalendarDays],['Idées',Lightbulb],['Publications',FileText]] as const;
export default function MemberPortal({preview=false}:{preview?:boolean}){
 const [calendarMonth,setCalendarMonth]=useState(()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1)}),[view,setView]=useState('Accueil'),[pubs,setPubs]=useState<Pub[]>([]),[news,setNews]=useState<News[]>([]),[ideas,setIdeas]=useState<Idea[]>([]),[loading,setLoading]=useState(true),[ideaOpen,setIdeaOpen]=useState(false),[postOpen,setPostOpen]=useState(false),[title,setTitle]=useState(''),[body,setBody]=useState('');
 async function refresh(){if(!supabase)return;setLoading(true);const [p,n,i]=await Promise.all([supabase.from('ca_publications').select('id,title,body,published,category,event_date,created_at').eq('published',true).order('created_at',{ascending:false}),supabase.from('ca_news_items').select('id,title,body,topic,news_type,published_at,event_date,kind,source_refs').order('published_at',{ascending:false}).limit(500),supabase.from('ca_ideas').select('id,title,body,status,created_at').order('created_at',{ascending:false})]);setPubs((p.data||[]) as Pub[]);setNews((n.data||[]) as News[]);setIdeas((i.data||[]) as Idea[]);setLoading(false);}
 useEffect(()=>{void refresh();const client=supabase;if(!client)return;const channel=client.channel('member-portal-live').on('postgres_changes',{event:'*',schema:'public',table:'ca_news_items'},()=>void refresh()).on('postgres_changes',{event:'*',schema:'public',table:'ca_publications'},()=>void refresh()).on('postgres_changes',{event:'*',schema:'public',table:'ca_ideas'},()=>void refresh()).subscribe();return()=>{void client.removeChannel(channel);};},[]);
 const meetings=useMemo(()=>news.filter(n=>n.news_type==='Compte rendu CA'||/compte rendu|réunion|ca\b/i.test(n.topic+' '+n.title)),[news]);
 const externalIdeas=useMemo(()=>news.filter(n=>n.kind==='initiative_ffmc'),[news]);
 const events=useMemo(()=>[...pubs.filter(p=>p.event_date).map(p=>({date:p.event_date!,title:p.title,type:p.category||'Action'})),...news.filter(n=>n.event_date).map(n=>({date:n.event_date!,title:n.title,type:/réunion|compte rendu|ca\b/i.test(n.news_type+' '+n.topic+' '+n.title)?'Réunion':n.news_type||'Action'}))].sort((a,b)=>a.date.localeCompare(b.date)),[pubs,news]);
 const calendar=useMemo(()=>{const y=calendarMonth.getFullYear(),m=calendarMonth.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),offset=(first.getDay()+6)%7;return Array.from({length:Math.ceil((offset+days)/7)*7},(_,i)=>{const day=i-offset+1;if(day<1||day>days)return null;const date=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;return {day,date,events:events.filter(e=>e.date===date)}})},[calendarMonth,events]);
 async function submitIdea(e:React.FormEvent){e.preventDefault();if(!supabase)return;const {error}=await supabase.from('ca_ideas').insert({title:title.trim(),body:body.trim()});if(error)return toast.error('Impossible d’ajouter l’idée.');setTitle('');setBody('');setIdeaOpen(false);toast.success('Idée proposée au CA.');await refresh();}
 async function submitPost(e:React.FormEvent){e.preventDefault();if(!supabase)return;const {error}=await supabase.from('ca_publications').insert({title:title.trim(),body:body.trim(),published:false,category:'Proposition de publication'});if(error)return toast.error('Impossible d’envoyer la publication.');setTitle('');setBody('');setPostOpen(false);toast.success('Publication envoyée au coordinateur pour validation.');}
 const Card=({n}:{n:News})=><article className="member-card"><span className="member-chip">{n.news_type||n.topic}</span><h3>{decode(n.title)}</h3><p>{decode(n.body)}</p>{n.published_at&&<small>{new Date(n.published_at).toLocaleDateString('fr-FR')}</small>}{n.source_refs&&n.source_refs.length>0&&<details className="member-sources"><summary>Sources ({n.source_refs.length})</summary><ul>{n.source_refs.map((s,i)=>{const url=safeUrl(s.url);return <li key={i}>{url?<a href={url} target="_blank" rel="noreferrer">{decode(s.label)} ↗</a>:decode(s.label)}{s.date&&<small> · {s.date}</small>}</li>})}</ul></details>}</article>;
 return <div className="ca-portal">{preview&&<div className="preview-banner">Aperçu de l’espace membre du CA</div>}<header className="ca-head"><div className="member-brand"><span>06</span><strong>FFMC · ESPACE CA</strong></div><button className="secondary" onClick={refresh}><RefreshCw size={15}/> Actualiser</button></header><nav className="ca-tabs">{tabs.map(([t,I])=><button key={t} className={view===t?'active':''} onClick={()=>setView(t)}><I size={17}/>{t}</button>)}</nav><main className="ca-content">{loading?<p className="muted">Chargement de l’espace CA…</p>:<>
 {view==='Accueil'&&<><div className="ca-welcome"><div><p className="eyebrow">TABLEAU DE BORD DU CA</p><h1>Bonjour 👋</h1><p>Les informations utiles au conseil d’administration, sans le courrier privé du coordinateur.</p></div><Bell size={34}/></div><div className="ca-metrics"><button onClick={()=>setView('Actualités')}><strong>{news.length+pubs.length}</strong><span>informations</span></button><button onClick={()=>setView('Réunions')}><strong>{meetings.length}</strong><span>comptes rendus</span></button><button onClick={()=>setView('Agenda')}><strong>{events.length}</strong><span>dates à l’agenda</span></button><button onClick={()=>setView('Idées')}><strong>{ideas.length+externalIdeas.length}</strong><span>idées à regarder</span></button></div><h2 className="below">À voir par le CA</h2><div className="member-grid">{news.slice(0,4).map(n=><Card key={n.id} n={n}/>)}</div></>}
 {view==='Actualités'&&<><div className="ca-title"><div><p className="eyebrow">INFORMATIONS & NEWS</p><h1>Actualités du CA et de la FFMC 06</h1></div></div><div className="member-grid">{news.map(n=><Card key={n.id} n={n}/>)}</div><div className="below"><SharedMail/></div></>}
 {view==='Réunions'&&<><div className="ca-title"><p className="eyebrow">RÉUNIONS DU CA</p><h1>Comptes rendus et décisions</h1><p className="subtitle">Les comptes rendus PDF validés et les décisions partagées apparaissent ici.</p></div><div className="member-grid">{meetings.map(n=><Card key={n.id} n={n}/>)}</div></>}
 {view==='Agenda'&&<><div className="ca-title ca-row"><div><p className="eyebrow">AGENDA DU CA</p><h1>Actions & réunions</h1></div><div className="calendar-nav"><button className="secondary" onClick={()=>setCalendarMonth(d=>new Date(d.getFullYear(),d.getMonth()-1,1))}>‹</button><strong>{calendarMonth.toLocaleDateString('fr-FR',{month:'long',year:'numeric'})}</strong><button className="secondary" onClick={()=>setCalendarMonth(d=>new Date(d.getFullYear(),d.getMonth()+1,1))}>›</button></div></div><div className="ca-calendar"><div className="calendar-weekdays">{['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'].map(d=><strong key={d}>{d}</strong>)}</div><div className="calendar-grid">{calendar.map((cell,i)=><div key={i} className={'calendar-day '+(!cell?'calendar-empty':'')}>{cell&&<><span>{cell.day}</span>{cell.events.map((e,j)=><div key={j} className={'calendar-event '+(/réunion/i.test(e.type)?'meeting':'action')} title={e.title}><small>{e.type}</small><b>{e.title}</b></div>)}</>}</div>)}</div></div>{!events.length&&<p className="muted">Les actions et réunions datées apparaîtront automatiquement dans le calendrier.</p>}</>}
 {view==='Idées'&&<><div className="ca-title ca-row"><div><p className="eyebrow">BOÎTE À IDÉES</p><h1>Proposer et découvrir</h1></div><button className="primary" onClick={()=>{setTitle('');setBody('');setIdeaOpen(true)}}><Plus size={16}/> Ajouter une idée</button></div>{externalIdeas.length>0&&<><h2>Idées repérées dans les autres antennes</h2><div className="member-grid">{externalIdeas.map(n=><Card key={n.id} n={n}/>)}</div></>}<h2 className="below">Idées proposées par le CA</h2><div className="member-grid">{ideas.map(i=><article className="member-card" key={i.id}><span className="member-chip">{i.status}</span><h3>{i.title}</h3><p>{i.body}</p></article>)}</div></>}
 {view==='Publications'&&<><div className="ca-title ca-row"><div><p className="eyebrow">PUBLICATIONS</p><h1>Informations publiées au CA</h1></div><button className="primary" onClick={()=>{setTitle('');setBody('');setPostOpen(true)}}><Plus size={16}/> Proposer une publication</button></div><p className="subtitle">Une proposition d’un membre est envoyée au coordinateur en brouillon avant publication.</p><div className="publications">{pubs.map(p=><article className="publication" key={p.id}><span className="member-chip">{p.category||'Publication'}</span><h2>{p.title}</h2><div className="publication-body">{p.body}</div></article>)}</div></>}
 </>}</main>{(ideaOpen||postOpen)&&<div className="ca-modal" onMouseDown={()=>{setIdeaOpen(false);setPostOpen(false)}}><form onMouseDown={e=>e.stopPropagation()} onSubmit={ideaOpen?submitIdea:submitPost}><h2>{ideaOpen?'Nouvelle idée':'Proposer une publication'}</h2><p>{postOpen?'Elle sera relue par le coordinateur avant d’être visible par le CA.':'Décrivez simplement votre proposition.'}</p><label>Titre<input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Description<textarea required rows={7} maxLength={10000} value={body} onChange={e=>setBody(e.target.value)}/></label><div className="form-actions"><button type="button" className="secondary" onClick={()=>{setIdeaOpen(false);setPostOpen(false)}}>Annuler</button><button className="primary">Envoyer</button></div></form></div>}<Toaster richColors position="bottom-right"/></div>;
}