import {useEffect,useMemo,useState} from 'react';
import {Check,ChevronDown,ChevronUp,Copy,MapPin,Plus,Trash2,X} from 'lucide-react';
import {supabase} from './lib/backend';
import {toast} from 'sonner';
type RMC={id:string;name:string;location:string;event_date:string|null;profile:string;notes:string;status:string};
type Item={id:string;rmc_id:string;category:string;label:string;required:boolean;ready:boolean;sort_order:number;quantity:number;notes:string};
type CatalogItem={id:string;category:string;label:string;sort_order:number};
const profiles=['À définir','Relais Calmos full (ex. Escragnolles)','Relais Calmos avec aide mairie (ex. Guillaumes)','Salon moto avec aide mairie (ex. Grasse)'];
const template=[
['Base stand','Frigo'],['Base stand','Sono + câbles sono'],['Base stand','Caisse à outil'],['Base stand','Compresseur'],['Base stand','Groupe électrogène'],
['Affichage','Banderolles FFMC'],['Affichage','Flammes FFMC'],['Affichage','Banderolles Calmos'],['Affichage','Flammes Calmos'],['Affichage','Panneaux rigides Calmos'],['Affichage','Panneau déroulable'],['Affichage','Chasubles'],['Affichage','Drapeaux FFMC'],
['Logistique','Caisse FFMC'],['Logistique','Rallonge électrique enroulable'],['Logistique','Multiprise'],['Logistique','Boissons (Coca, Ice Tea, etc.)'],['Logistique','Cafetières'],['Logistique','Fournitures café (dosettes, sucre, etc.)'],['Logistique','Thé'],['Logistique',"Bouteilles d'eau"],['Logistique','Sandows, cordes, pinces, rislan'],['Logistique','Trousse avec ciseaux/cutter'],['Logistique','Caisses T-shirts'],
['Goodies','Tours de cou'],['Goodies','Verres FFMC'],['Goodies','Motocollants'],['Goodies','Cochon tirelire & boîte à dons'],
['Papiers',"Bulletins adhésion"],['Papiers','Magazines & prospectus'],['Papiers','Feuille suivi de ventes'],['Papiers','Feuille de présence']
] as const;
const profileSkip:Record<string,string[]>={
 'Relais Calmos avec aide mairie (ex. Guillaumes)':['Groupe électrogène'],
 'Salon moto avec aide mairie (ex. Grasse)':['Groupe électrogène','Compresseur']
};
export default function RMCPortal(){
 const [rmcs,setRmcs]=useState<RMC[]>([]),[items,setItems]=useState<Item[]>([]),[catalog,setCatalog]=useState<CatalogItem[]>([]),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[editingChecklist,setEditingChecklist]=useState(false),[showMaterial,setShowMaterial]=useState(true),[editingInfo,setEditingInfo]=useState(false),[draft,setDraft]=useState({name:'',location:'',event_date:'',profile:profiles[0]});
 async function load(){if(!supabase)return;const [{data:r},{data:i},{data:cat}]=await Promise.all([supabase.from('ca_rmc').select('*').order('event_date',{ascending:false}),supabase.from('ca_rmc_items').select('*').order('sort_order'),supabase.from('ca_rmc_catalog').select('*').order('sort_order')]);setRmcs((r||[]) as RMC[]);setItems((i||[]) as Item[]);setCatalog((cat||[]) as CatalogItem[]);if(!selected&&r?.[0])setSelected(r[0].id)}
 useEffect(()=>{void load()},[]);
 async function create(e:React.FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);const {data,error}=await supabase.from('ca_rmc').insert({...draft,event_date:draft.event_date||null,status:'À préparer',notes:''}).select().single();if(error){setBusy(false);return toast.error(error.message)}const skip=profileSkip[draft.profile]||[];const rows=template.filter(([,label])=>!skip.includes(label)).map(([category,label],n)=>({rmc_id:data.id,category,label,sort_order:n,required:true,ready:false,quantity:label==='Caisses T-shirts'?2:1,notes:''}));const ins=await supabase.from('ca_rmc_items').insert(rows);setBusy(false);if(ins.error)return toast.error(ins.error.message);setDraft({name:'',location:'',event_date:'',profile:profiles[0]});setSelected(data.id);toast.success('RMC créé avec sa checklist adaptée.');await load()}
 async function patchItem(i:Item,patch:Partial<Item>){setItems(v=>v.map(x=>x.id===i.id?{...x,...patch}:x));const {error}=await supabase!.from('ca_rmc_items').update(patch).eq('id',i.id);if(error){toast.error(error.message);await load()}}
 async function setRequired(cat:CatalogItem,required:boolean){if(!supabase||!selected)return;const existing=items.find(i=>i.rmc_id===selected&&i.label===cat.label);if(required){if(existing){await supabase.from('ca_rmc_items').update({required:true}).eq('id',existing.id)}else{await supabase.from('ca_rmc_items').insert({rmc_id:selected,category:cat.category,label:cat.label,sort_order:cat.sort_order,required:true,ready:false,quantity:cat.label==='Caisses T-shirts (x2)'?2:1,notes:''})}}else if(existing){await supabase.from('ca_rmc_items').delete().eq('id',existing.id)}await load()}
 async function addItem(){if(!supabase||!selected)return;const label=prompt('Matériel / élément à ajouter');if(!label?.trim())return;const category=prompt('Catégorie','Logistique')||'Autre';const {error}=await supabase.from('ca_rmc_items').insert({rmc_id:selected,label:label.trim(),category,sort_order:currentItems.length+100,quantity:1,notes:''});if(error)return toast.error(error.message);await load()}
 async function removeItem(i:Item){if(!confirm('Retirer « '+i.label+' » de cette checklist ?'))return;const {error}=await supabase!.from('ca_rmc_items').delete().eq('id',i.id);if(error)return toast.error(error.message);await load()}
 async function removeRmc(r:RMC){if(!confirm('Supprimer le RMC « '+r.name+' » et sa checklist ?'))return;const {error}=await supabase!.from('ca_rmc').delete().eq('id',r.id);if(error)return toast.error(error.message);setSelected('');await load()}
 async function duplicate(r:RMC){const name=prompt('Nom du nouveau RMC',r.name+' — copie');if(!name?.trim())return;const date=prompt('Date (AAAA-MM-JJ)','')||'';const {data:n,error}=await supabase!.from('ca_rmc').insert({name:name.trim(),location:r.location,event_date:date||null,profile:r.profile,status:'À préparer',notes:r.notes||''}).select().single();if(error)return toast.error(error.message);const source=items.filter(i=>i.rmc_id===r.id);const {error:ie}=await supabase!.from('ca_rmc_items').insert(source.map(i=>({rmc_id:n.id,category:i.category,label:i.label,required:i.required,ready:false,sort_order:i.sort_order,quantity:i.quantity,notes:i.notes})));if(ie)return toast.error(ie.message);setSelected(n.id);toast.success('RMC dupliqué.');await load()}
 async function patchRmc(r:RMC,patch:Partial<RMC>){setRmcs(v=>v.map(x=>x.id===r.id?{...x,...patch}:x));const {error}=await supabase!.from('ca_rmc').update({...patch,updated_at:new Date().toISOString()}).eq('id',r.id);if(error){toast.error(error.message);await load()}}
 const current=rmcs.find(r=>r.id===selected),currentItems=items.filter(i=>i.rmc_id===selected),categories=useMemo(()=>[...new Set(currentItems.map(i=>i.category))],[currentItems]);
 return <section><div className="section-head"><div><p className="eyebrow">RELAIS MOTARD CALMOS</p><h2>Préparation des RMC</h2><p className="muted">Prépare le matériel par opération, puis coche ce qui est réellement prêt.</p></div></div>
 <form className="member-invite" onSubmit={create}><div className="invite-main"><label>Nom du RMC<input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Ex. RMC Guillaumes"/></label><label>Lieu<input required value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})} placeholder="Guillaumes"/></label></div><div className="invite-options"><label>Date<input type="date" value={draft.event_date} onChange={e=>setDraft({...draft,event_date:e.target.value})}/></label><label>Profil<select value={draft.profile} onChange={e=>setDraft({...draft,profile:e.target.value})}>{profiles.map(p=><option key={p}>{p}</option>)}</select></label><button className="primary" disabled={busy}><Plus size={16}/>Créer le RMC</button></div></form>
 <div className="filters">{rmcs.map(r=><button key={r.id} className={selected===r.id?'chosen':''} onClick={()=>setSelected(r.id)}>{r.name}</button>)}</div>
 {current?<><div className="rmc-summary"><div>{editingInfo?<div className="rmc-info-edit"><label>Nom<input value={current.name} onChange={e=>setRmcs(v=>v.map(x=>x.id===current.id?{...x,name:e.target.value}:x))}/></label><label>Lieu<input value={current.location} onChange={e=>setRmcs(v=>v.map(x=>x.id===current.id?{...x,location:e.target.value}:x))}/></label><label>Date facultative<input type="date" value={current.event_date||''} onChange={e=>setRmcs(v=>v.map(x=>x.id===current.id?{...x,event_date:e.target.value||null}:x))}/></label><label>Profil<select value={current.profile} onChange={e=>setRmcs(v=>v.map(x=>x.id===current.id?{...x,profile:e.target.value}:x))}>{profiles.map(p=><option key={p}>{p}</option>)}</select></label><div className="sharing-actions"><button className="primary" onClick={async()=>{await patchRmc(current,{name:current.name.trim(),location:current.location,event_date:current.event_date,profile:current.profile});setEditingInfo(false)}}>Enregistrer</button><button className="secondary" onClick={async()=>{setEditingInfo(false);await load()}}>Annuler</button></div></div>:<><h2>{current.name}</h2><p className="muted"><MapPin size={14} className="inline"/> {current.location}{current.event_date?' · '+new Date(current.event_date+'T12:00:00').toLocaleDateString('fr-FR'):''} · {current.profile}</p><button className="secondary" onClick={()=>setEditingInfo(true)}>Modifier les informations</button></>}</div><strong>{currentItems.length} élément{currentItems.length>1?'s':''} nécessaire{currentItems.length>1?'s':''}</strong></div>
 <div className="rmc-material-head"><button className="secondary rmc-toggle-material" onClick={()=>setShowMaterial(v=>!v)}>{showMaterial?<ChevronUp size={16}/>:<ChevronDown size={16}/>} Matériel nécessaire</button><button className="secondary" onClick={()=>setEditingChecklist(v=>!v)}>{editingChecklist?'Terminer':'Modifier la liste'}</button></div>
 {showMaterial&&<div className="rmc-simple-list">{currentItems.length===0?<p className="muted">Aucun matériel sélectionné.</p>:categories.map(cat=><div className="rmc-simple-category" key={cat}><strong>{cat}</strong>{currentItems.filter(i=>i.category===cat).map(i=><div className="rmc-simple-row" key={i.id}>{i.label}</div>)}</div>)}</div>}
 {editingChecklist&&<div className="rmc-dropdown"><p className="muted">Modification de la liste : coche ou décoche le matériel nécessaire.</p>{[...new Set(catalog.map(x=>x.category))].map(cat=><section key={cat}><h3>{cat}</h3><div className="rmc-catalog-list">{catalog.filter(x=>x.category===cat).map(x=>{const yes=currentItems.some(i=>i.label===x.label);return <label className={'rmc-need-row '+(yes?'selected':'')} key={x.id}><input type="checkbox" checked={yes} onChange={e=>setRequired(x,e.target.checked)}/><span>{x.label}</span>{yes&&<Check size={17}/>}</label>})}</div></section>)}</div>}
 <div className="sharing-actions"><button className="secondary" onClick={addItem}><Plus size={14}/> Ajouter un élément</button><button className="secondary" onClick={()=>duplicate(current)}><Copy size={14}/> Dupliquer</button><button className="secondary" onClick={()=>removeRmc(current)}><Trash2 size={14}/> Supprimer</button></div></>:<p className="muted">Crée ton premier RMC pour définir le matériel nécessaire.</p>}</section>
}