import {useEffect,useState} from 'react';
import {FileText,Plus,Trash2} from 'lucide-react';
import {supabase} from './lib/backend';
import {toast} from 'sonner';
type Entry={id:string;kind:string;title:string;body:string;event_date?:string;status:string;author_name?:string;created_at:string;linked_table?:string;linked_id?:string};
export default function SecretariatPortal(){
 const [items,setItems]=useState<Entry[]>([]),[open,setOpen]=useState(false),[kind,setKind]=useState('compte_rendu'),[title,setTitle]=useState(''),[body,setBody]=useState(''),[date,setDate]=useState(''),[status,setStatus]=useState('publie'),[editing,setEditing]=useState<Entry|null>(null),[agendaItems,setAgendaItems]=useState<{title:string;date:string;notes:string}[]>([]);
 async function load(){if(!supabase)return;const {data,error}=await supabase.from('ca_secretariat_entries').select('*').order('created_at',{ascending:false});if(error)toast.error(error.message);else setItems((data||[]) as Entry[])}
 useEffect(()=>{void load()},[]);
 async function save(e:React.FormEvent){e.preventDefault();if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const author=user.user_metadata?.display_name||user.email||'Secrétariat';const payload={kind,title:title.trim(),body:body.trim(),event_date:date||null,status,author_id:user.id,author_name:author};if(editing){const {error}=await supabase.from('ca_secretariat_entries').update(payload).eq('id',editing.id);if(error)return toast.error(error.message);if(editing.linked_table&&editing.linked_id){if(editing.linked_table==='records')await supabase.from('records').update({kind:kind==='compte_rendu'?'Réunion':'Action',title:payload.title,status:kind==='compte_rendu'?'Terminé':'À décider',owner:author,due:payload.event_date,notes:payload.body}).eq('id',editing.linked_id);if(editing.linked_table==='ca_publications')await supabase.from('ca_publications').update({title:payload.title,body:payload.body,published:status==='publie',event_date:payload.event_date}).eq('id',editing.linked_id)}toast.success('Modification enregistrée partout');}else{const {data:entry,error}=await supabase.from('ca_secretariat_entries').insert(payload).select('id').single();if(error)return toast.error(error.message);let linked_table:string|null=null,linked_id:string|null=null;if(status==='publie'&&kind==='compte_rendu'){const {data:x}=await supabase.from('records').insert({kind:'Réunion',title:payload.title,status:'Terminé',owner:author,due:payload.event_date,notes:payload.body,next:''}).select('id').single();if(x){linked_table='records';linked_id=x.id}}else if(status==='publie'&&kind==='action'){const {data:x}=await supabase.from('records').insert({kind:'Action',title:payload.title,status:'À décider',owner:author,due:payload.event_date,notes:payload.body,next:''}).select('id').single();if(x){linked_table='records';linked_id=x.id}}else if(status==='publie'&&kind==='information'){const {data:x}=await supabase.from('ca_publications').insert({title:payload.title,body:payload.body,published:true,category:'Secrétariat',event_date:payload.event_date}).select('id').single();if(x){linked_table='ca_publications';linked_id=x.id}}if(linked_id)await supabase.from('ca_secretariat_entries').update({linked_table,linked_id}).eq('id',entry.id);if(kind==='compte_rendu'&&agendaItems.length){for(const a of agendaItems){const {data:rec,error:re}=await supabase.from('records').insert({kind:'Action',title:a.title.trim(),status:'À décider',owner:author,due:a.date,notes:a.notes.trim()||('Issu du compte rendu : '+payload.title),next:''}).select('id').single();if(!re&&rec)await supabase.from('ca_secretariat_agenda_items').insert({entry_id:entry.id,title:a.title.trim(),event_date:a.date,notes:a.notes.trim(),record_id:rec.id})}}toast.success(status==='publie'?'Information publiée et synchronisée':'Brouillon enregistré')}setTitle('');setBody('');setDate('');setAgendaItems([]);setEditing(null);setOpen(false);await load()}
 async function remove(x:Entry){if(!supabase||!confirm('Supprimer cette entrée et ses copies liées ?'))return;if(x.linked_table&&x.linked_id){const {error:linkedError}=await supabase.from(x.linked_table).delete().eq('id',x.linked_id);if(linkedError)return toast.error('Suppression liée impossible : '+linkedError.message)}const {error}=await supabase.from('ca_secretariat_entries').delete().eq('id',x.id);if(error)toast.error(error.message);else{toast.success('Supprimé partout');await load()}}
 function edit(x:Entry){setEditing(x);setKind(x.kind);setTitle(x.title);setBody(x.body);setDate(x.event_date||'');setStatus(x.status);setAgendaItems([]);setOpen(true);window.scrollTo({top:0,behavior:'smooth'})}
 function addAgenda(){setAgendaItems(v=>[...v,{title:'',date:'',notes:''}])}
 function agendaChange(i:number,k:'title'|'date'|'notes',v:string){setAgendaItems(a=>a.map((x,n)=>n===i?{...x,[k]:v}:x))}
 function agendaRemove(i:number){setAgendaItems(a=>a.filter((_,n)=>n!==i))}
 const label=(k:string)=>({compte_rendu:'Compte rendu',information:'Information',decision:'Décision',action:'Action'} as any)[k]||k;
 return <section className="secretariat-portal"><div className="secretariat-head"><div><p className="eyebrow">SECRÉTARIAT · FFMC 06</p><h1>Suivi du CA</h1><p className="subtitle">Centraliser les comptes rendus, décisions, informations et actions à transmettre.</p></div><button className="primary" onClick={()=>{setEditing(null);setTitle('');setBody('');setDate('');setOpen(v=>!v)}}><Plus size={16}/>Nouvelle entrée</button></div>
 {open&&<form className="member-invite secretariat-form" onSubmit={save}><div className="invite-intro"><span className="invite-icon"><FileText size={21}/></span><div><h3>{editing?'Modifier l’entrée':'Ajouter au suivi du CA'}</h3><p>Choisissez le type d’information puis publiez-la ou conservez-la en brouillon.</p></div></div><div className="secretariat-fields"><label><span>Type</span><select value={kind} onChange={e=>setKind(e.target.value)}><option value="compte_rendu">Compte rendu</option><option value="information">Information</option><option value="decision">Décision</option><option value="action">Action / prochaine étape</option></select></label><label><span>Date liée</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="wide"><span>Titre</span><input required placeholder="Ex. Réunion CA du 30 septembre" value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="wide"><span>Contenu</span><textarea required rows={8} placeholder="Participants, sujets abordés, décisions, points à suivre…" value={body} onChange={e=>setBody(e.target.value)}/></label>{kind==='compte_rendu'&&<div className="wide secretariat-agenda"><div className="secretariat-agenda-head"><div><strong>Dates à ajouter à l’agenda</strong><small>Ajoutez ici les échéances et événements cités dans le compte rendu.</small></div><button type="button" className="secondary" onClick={addAgenda}><Plus size={14}/> Ajouter une date</button></div>{agendaItems.map((a,i)=><div className="secretariat-agenda-row" key={i}><input required placeholder="Événement / action" value={a.title} onChange={e=>agendaChange(i,'title',e.target.value)}/><input required type="date" value={a.date} onChange={e=>agendaChange(i,'date',e.target.value)}/><input placeholder="Note (optionnel)" value={a.notes} onChange={e=>agendaChange(i,'notes',e.target.value)}/><button type="button" className="text-btn danger" onClick={()=>agendaRemove(i)}><Trash2 size={15}/></button></div>)}</div>}<label><span>Publication</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="publie">Visible par le CA</option><option value="brouillon">Brouillon</option></select></label></div><div className="secretariat-actions"><button type="button" className="secondary" onClick={()=>{setOpen(false);setEditing(null)}}>Annuler</button><button className="primary">{editing?'Enregistrer les modifications':status==='publie'?'Publier au CA':'Enregistrer le brouillon'}</button></div></form>}
 <div className="secretariat-list">{items.length===0?<div className="empty"><FileText size={25}/><h3>Aucune entrée</h3><p>Les comptes rendus et informations saisis apparaîtront ici.</p></div>:items.map(x=><article className="secretariat-card" key={x.id}><div className="record-top"><span className="member-chip">{label(x.kind)}</span><span className={'secretariat-status '+x.status}>{x.status==='publie'?'Publié':'Brouillon'}</span></div><h3>{x.title}</h3>{x.event_date&&<time>{new Date(x.event_date+'T12:00:00').toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'})}</time>}<p>{x.body}</p><footer><small>{x.author_name||'Secrétariat'}</small><div className="secretariat-card-actions"><button className="text-btn" onClick={()=>edit(x)}>Modifier</button><button className="text-btn danger" onClick={()=>void remove(x)}><Trash2 size={14}/>Supprimer</button></div></footer></article>)}</div></section>
}