import {useEffect,useState} from 'react';
import {FileText,Plus,Trash2} from 'lucide-react';
import {supabase} from './lib/backend';
import {toast} from 'sonner';
type Entry={id:string;kind:string;title:string;body:string;event_date?:string;status:string;author_name?:string;created_at:string};
export default function SecretariatPortal(){
 const [items,setItems]=useState<Entry[]>([]),[open,setOpen]=useState(false),[kind,setKind]=useState('compte_rendu'),[title,setTitle]=useState(''),[body,setBody]=useState(''),[date,setDate]=useState(''),[status,setStatus]=useState('publie');
 async function load(){if(!supabase)return;const {data,error}=await supabase.from('ca_secretariat_entries').select('*').order('created_at',{ascending:false});if(error)toast.error(error.message);else setItems((data||[]) as Entry[])}
 useEffect(()=>{void load()},[]);
 async function save(e:React.FormEvent){e.preventDefault();if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const author=user.user_metadata?.display_name||user.email||'Secrétariat';const {error}=await supabase.from('ca_secretariat_entries').insert({kind,title:title.trim(),body:body.trim(),event_date:date||null,status,author_id:user.id,author_name:author});if(error)return toast.error(error.message);if(status==='publie'){if(kind==='compte_rendu'){const {error:linkError}=await supabase.from('records').insert({kind:'Réunion',title:title.trim(),status:'Terminé',owner:author,due:date||null,notes:body.trim(),next:''});if(linkError)toast.error('Compte rendu enregistré, mais ajout à Réunions impossible : '+linkError.message)}else if(kind==='action'){const {error:linkError}=await supabase.from('records').insert({kind:'Action',title:title.trim(),status:'À décider',owner:author,due:date||null,notes:body.trim(),next:''});if(linkError)toast.error('Action enregistrée, mais ajout à l’agenda impossible : '+linkError.message)}else if(kind==='information'){const {error:linkError}=await supabase.from('ca_publications').insert({title:title.trim(),body:body.trim(),published:true,category:'Secrétariat',event_date:date||null});if(linkError)toast.error('Information enregistrée, mais publication au CA impossible : '+linkError.message)}}setTitle('');setBody('');setDate('');setOpen(false);toast.success(status==='publie'?'Information publiée et synchronisée':'Brouillon enregistré');await load()}
 async function remove(id:string){if(!supabase||!confirm('Supprimer cette entrée ?'))return;const {error}=await supabase.from('ca_secretariat_entries').delete().eq('id',id);if(error)toast.error(error.message);else await load()}
 const label=(k:string)=>({compte_rendu:'Compte rendu',information:'Information',decision:'Décision',action:'Action'} as any)[k]||k;
 return <section className="secretariat-portal"><div className="secretariat-head"><div><p className="eyebrow">SECRÉTARIAT · FFMC 06</p><h1>Suivi du CA</h1><p className="subtitle">Centraliser les comptes rendus, décisions, informations et actions à transmettre.</p></div><button className="primary" onClick={()=>setOpen(v=>!v)}><Plus size={16}/>Nouvelle entrée</button></div>
 {open&&<form className="member-invite secretariat-form" onSubmit={save}><div className="invite-intro"><span className="invite-icon"><FileText size={21}/></span><div><h3>Ajouter au suivi du CA</h3><p>Choisissez le type d’information puis publiez-la ou conservez-la en brouillon.</p></div></div><div className="secretariat-fields"><label><span>Type</span><select value={kind} onChange={e=>setKind(e.target.value)}><option value="compte_rendu">Compte rendu</option><option value="information">Information</option><option value="decision">Décision</option><option value="action">Action / prochaine étape</option></select></label><label><span>Date liée</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="wide"><span>Titre</span><input required placeholder="Ex. Réunion CA du 30 septembre" value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="wide"><span>Contenu</span><textarea required rows={8} placeholder="Participants, sujets abordés, décisions, points à suivre…" value={body} onChange={e=>setBody(e.target.value)}/></label><label><span>Publication</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="publie">Visible par le CA</option><option value="brouillon">Brouillon</option></select></label></div><div className="secretariat-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Annuler</button><button className="primary">{status==='publie'?'Publier au CA':'Enregistrer le brouillon'}</button></div></form>}
 <div className="secretariat-list">{items.length===0?<div className="empty"><FileText size={25}/><h3>Aucune entrée</h3><p>Les comptes rendus et informations saisis apparaîtront ici.</p></div>:items.map(x=><article className="secretariat-card" key={x.id}><div className="record-top"><span className="member-chip">{label(x.kind)}</span><span className={'secretariat-status '+x.status}>{x.status==='publie'?'Publié':'Brouillon'}</span></div><h3>{x.title}</h3>{x.event_date&&<time>{new Date(x.event_date+'T12:00:00').toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'})}</time>}<p>{x.body}</p><footer><small>{x.author_name||'Secrétariat'}</small><button className="text-btn" onClick={()=>void remove(x.id)}><Trash2 size={14}/>Supprimer</button></footer></article>)}</div></section>
}