import {useEffect,useMemo,useState} from 'react';
import {Euro,Plus,Trash2,ExternalLink} from 'lucide-react';
import {supabase} from './lib/backend';
import {toast} from 'sonner';
type Entry={id:string;entry_date:string;kind:'Recette'|'Dépense';category:string;label:string;amount_cents:number;notes:string;receipt_url?:string;created_by_name?:string};
const categories=['Cotisations','Dons','Événements','Déplacements','Communication','Matériel','Remboursements','Frais bancaires','Autre'];
const eur=(c:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(c/100);
export default function TreasuryPortal(){
 const [items,setItems]=useState<Entry[]>([]),[open,setOpen]=useState(false),[kind,setKind]=useState<'Recette'|'Dépense'>('Dépense'),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[category,setCategory]=useState('Autre'),[label,setLabel]=useState(''),[amount,setAmount]=useState(''),[notes,setNotes]=useState(''),[receipt,setReceipt]=useState('');
 async function load(){if(!supabase)return;const {data,error}=await supabase.from('ca_treasury_entries').select('*').order('entry_date',{ascending:false}).order('created_at',{ascending:false});if(error)toast.error('Impossible de charger la trésorerie.');else setItems((data||[]) as Entry[])}
 useEffect(()=>{void load()},[]);
 const totals=useMemo(()=>{let income=0,expense=0;for(const x of items)(x.kind==='Recette'?income+=x.amount_cents:expense+=x.amount_cents);return{income,expense,balance:income-expense}},[items]);
 async function save(e:React.FormEvent){e.preventDefault();if(!supabase)return;const cents=Math.round(Number(amount.replace(',','.'))*100);if(!Number.isFinite(cents)||cents<=0)return toast.error('Saisissez un montant valide.');const clean=receipt.trim();if(clean){try{const u=new URL(clean);if(!['http:','https:'].includes(u.protocol))throw Error()}catch{return toast.error('Le lien du justificatif doit être valide.')}}const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:m}=await supabase.from('ca_members').select('display_name').eq('user_id',user.id).maybeSingle();const {error}=await supabase.from('ca_treasury_entries').insert({entry_date:date,kind,category,label:label.trim(),amount_cents:cents,notes:notes.trim(),receipt_url:clean||null,created_by:user.id,created_by_name:m?.display_name||user.email});if(error)return toast.error(error.message);setLabel('');setAmount('');setNotes('');setReceipt('');setOpen(false);toast.success('Mouvement enregistré.');await load()}
 async function remove(x:Entry){if(!supabase||!confirm('Supprimer définitivement ce mouvement ?'))return;const {error}=await supabase.from('ca_treasury_entries').delete().eq('id',x.id);if(error)toast.error(error.message);else{toast.success('Mouvement supprimé.');await load()}}
 return <section className="secretariat-portal"><div className="secretariat-head"><div><p className="eyebrow">GESTION INTERNE · ACCÈS RESTREINT</p><h1>Trésorerie</h1><p className="subtitle">Suivi simple des recettes, dépenses et justificatifs de l’antenne.</p></div><button className="primary" onClick={()=>setOpen(v=>!v)}><Plus size={16}/>Nouveau mouvement</button></div>
 <div className="metrics"><div className="metric"><Euro size={20}/><strong>{eur(totals.income)}</strong><span>Recettes</span></div><div className="metric"><Euro size={20}/><strong>{eur(totals.expense)}</strong><span>Dépenses</span></div><div className="metric"><Euro size={20}/><strong>{eur(totals.balance)}</strong><span>Solde enregistré</span></div></div>
 {open&&<form className="member-invite secretariat-form" onSubmit={save}><div className="secretariat-fields"><label><span>Type</span><select value={kind} onChange={e=>setKind(e.target.value as any)}><option>Recette</option><option>Dépense</option></select></label><label><span>Date</span><input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label><span>Catégorie</span><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Montant (€)</span><input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0,00"/></label><label className="wide"><span>Libellé</span><input required maxLength={200} value={label} onChange={e=>setLabel(e.target.value)} placeholder="Ex. Impression des affiches"/></label><label className="wide"><span>Notes</span><textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label><label className="wide"><span>Lien du justificatif</span><input type="url" value={receipt} onChange={e=>setReceipt(e.target.value)} placeholder="https://…"/></label></div><div className="secretariat-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Annuler</button><button className="primary">Enregistrer</button></div></form>}
 <div className="secretariat-list">{items.length?items.map(x=><article className="secretariat-card" key={x.id}><div className="record-top"><span className="member-chip">{x.kind} · {x.category}</span><strong>{x.kind==='Dépense'?'-':'+'}{eur(x.amount_cents)}</strong></div><h3>{x.label}</h3>{x.notes&&<p>{x.notes}</p>}<footer><small>{new Date(x.entry_date+'T12:00:00').toLocaleDateString('fr-FR')} · {x.created_by_name||'FFMC 06'}</small><div className="secretariat-card-actions">{x.receipt_url&&<a className="text-btn" href={x.receipt_url} target="_blank" rel="noreferrer">Justificatif <ExternalLink size={14}/></a>}<button className="text-btn danger" onClick={()=>void remove(x)}><Trash2 size={14}/>Supprimer</button></div></footer></article>):<div className="empty"><Euro size={25}/><h3>Aucun mouvement</h3><p>Ajoutez la première recette ou dépense de l’antenne.</p></div>}</div></section>
}