import {useEffect,useRef,useState} from 'react';
import {CalendarDays,FileText,Mic,MicOff,Radio,Users} from 'lucide-react';
import {supabase} from './lib/backend';
import {toast} from 'sonner';

type Post={id:string;title:string;body:string;event_date:string|null;author_name:string;created_at:string};
type Event={id:string;title:string;event_date:string;location:string;instructions:string};
export default function VoltigeursPortal({role}:{role:string}){
 const manage=role==='coordinateur'||role==='charge_mission_voltigeurs';
 const [tab,setTab]=useState<'infos'|'events'|'radio'>('infos'),[posts,setPosts]=useState<Post[]>([]),[events,setEvents]=useState<Event[]>([]);
 const [title,setTitle]=useState(''),[body,setBody]=useState(''),[date,setDate]=useState(''),[location,setLocation]=useState('');
 const [mic,setMic]=useState(false),[joined,setJoined]=useState(false),[room,setRoom]=useState('');
 const stream=useRef<MediaStream|null>(null);
 async function load(){if(!supabase)return;const [{data:p},{data:e}]=await Promise.all([supabase.from('team_posts').select('*').eq('team','voltigeurs').order('created_at',{ascending:false}),supabase.from('team_events').select('*').eq('team','voltigeurs').order('event_date')]);setPosts((p||[]) as Post[]);setEvents((e||[]) as Event[])}
 useEffect(()=>{void load();return()=>{stream.current?.getTracks().forEach(t=>t.stop())}},[]);
 async function addPost(e:React.FormEvent){e.preventDefault();if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();const {data:m}=await supabase.from('ca_members').select('display_name').eq('user_id',user!.id).single();const {error}=await supabase.from('team_posts').insert({team:'voltigeurs',title,body,event_date:date||null,author_id:user!.id,author_name:m?.display_name||''});if(error)return toast.error(error.message);setTitle('');setBody('');setDate('');toast.success('Information partagée aux voltigeurs');void load()}
 async function addEvent(e:React.FormEvent){e.preventDefault();if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('team_events').insert({team:'voltigeurs',title,event_date:date,location,instructions:body,created_by:user!.id});if(error)return toast.error(error.message);setTitle('');setBody('');setDate('');setLocation('');toast.success('Événement ajouté');void load()}
 async function joinAudio(){try{const s=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});s.getAudioTracks().forEach(t=>t.enabled=false);stream.current=s;setMic(false);setJoined(true);setRoom(events[0]?.title||'Canal Voltigeurs');toast.success('Micro prêt. Il est coupé par défaut.')}catch{toast.error("Autorisez l'accès au micro pour utiliser la communication.")}}
 function toggleMic(on:boolean){stream.current?.getAudioTracks().forEach(t=>t.enabled=on);setMic(on)}
 function leave(){stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setJoined(false);setMic(false)}
 return <section><div className="member-admin-head"><div><p className="eyebrow">CORPS & ÉQUIPES · FFMC 06</p><h2>Voltigeurs</h2><p className="subtitle">Consignes, événements et communication opérationnelle.</p></div><span className="private">{manage?'Gestion Voltigeurs':'Voltigeur'}</span></div>
 <div className="filters"><button className={tab==='infos'?'chosen':''} onClick={()=>setTab('infos')}><FileText size={15}/> Informations</button><button className={tab==='events'?'chosen':''} onClick={()=>setTab('events')}><CalendarDays size={15}/> Événements</button><button className={tab==='radio'?'chosen':''} onClick={()=>setTab('radio')}><Radio size={15}/> Communication</button></div>
 {tab==='infos'&&<>{manage&&<form className="member-invite" onSubmit={addPost}><h3>Partager une information aux voltigeurs</h3><label>Titre<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Consigne / information<textarea required rows={4} value={body} onChange={e=>setBody(e.target.value)}/></label><label>Date liée (facultatif)<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="primary">Publier</button></form>}<div className="cards">{posts.map(p=><article className="record" key={p.id}><div className="record-top"><span className="badge">INFO VOLTIGEURS</span><small>{p.event_date||new Date(p.created_at).toLocaleDateString('fr-FR')}</small></div><h3>{p.title}</h3><p style={{whiteSpace:'pre-wrap'}}>{p.body}</p><div className="record-bottom"><span>{p.author_name||'FFMC 06'}</span></div></article>)}</div></>}
 {tab==='events'&&<>{manage&&<form className="member-invite" onSubmit={addEvent}><h3>Nouvel événement / dispositif</h3><label>Événement<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><div className="form-row"><label>Date<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Lieu<input value={location} onChange={e=>setLocation(e.target.value)}/></label></div><label>Consignes<textarea rows={4} value={body} onChange={e=>setBody(e.target.value)}/></label><button className="primary">Ajouter l’événement</button></form>}<div className="cards">{events.map(e=><article className="record" key={e.id}><div className="record-top"><span className="badge">{new Date(e.event_date+'T12:00:00').toLocaleDateString('fr-FR')}</span></div><h3>{e.title}</h3><p>{e.location}</p><p style={{whiteSpace:'pre-wrap'}}>{e.instructions}</p></article>)}</div></>}
 {tab==='radio'&&<div className="meeting-prompt" style={{maxWidth:620,margin:'20px auto',textAlign:'center'}}><Radio size={36}/><p className="eyebrow">COMMUNICATION MANIFESTATION</p><h2>{joined?room:'Canal Voltigeurs'}</h2><p>{joined?'Votre téléphone est prêt. Le micro démarre toujours coupé.':'Prépare le micro du téléphone avant le départ. Ne manipulez pas le téléphone en conduisant.'}</p>{!joined?<button className="primary" onClick={joinAudio}><Mic size={20}/> Préparer mon micro</button>:<><button onClick={()=>toggleMic(!mic)} style={{width:'100%',minHeight:150,fontSize:28,fontWeight:900,borderRadius:24,border:0}} className={mic?'primary':'secondary'}>{mic?<><Mic size={34}/> MICRO ON</>:<><MicOff size={34}/> MICRO OFF</>}</button><p><strong>{mic?'Micro ouvert':'Micro coupé'}</strong></p><button className="secondary" onClick={leave}>Quitter le canal</button></>}<div className="notice" style={{marginTop:20}}><Users size={18}/><span>Version de sécurité : contrôle du micro opérationnel. La transmission audio entre téléphones sera activée après validation du test terrain.</span></div></div>}
 </section>
}