import {useEffect,useRef,useState} from 'react';
import {CalendarDays,FileText,Map,Mic,MicOff,Radio,Users} from 'lucide-react';
import {lazy,Suspense} from 'react';
const LiveOperation=lazy(()=>import('./LiveOperation'));
import {supabase} from './lib/backend';
import {toast} from 'sonner';

type Post={id:string;title:string;body:string;event_date:string|null;author_name:string;created_at:string};
type Event={id:string;title:string;event_date:string;location:string;instructions:string};
export default function VoltigeursPortal({role}:{role:string}){
 const manage=role==='coordinateur'||role==='charge_mission_voltigeurs';
 const [tab,setTab]=useState<'infos'|'events'|'members'|'live'|'radio'>('infos'),[posts,setPosts]=useState<Post[]>([]),[events,setEvents]=useState<Event[]>([]),[members,setMembers]=useState<any[]>([]);
 const [title,setTitle]=useState(''),[body,setBody]=useState(''),[date,setDate]=useState(''),[location,setLocation]=useState('');
 const [mic,setMic]=useState(false),[joined,setJoined]=useState(false),[room,setRoom]=useState(''),[selectedEvent,setSelectedEvent]=useState('general'),[online,setOnline]=useState(0),[radioStatus,setRadioStatus]=useState('Hors ligne');
 const stream=useRef<MediaStream|null>(null),peers=useRef(new Map<string,RTCPeerConnection>()),radioChannel=useRef<any>(null),me=useRef<string>(''),audioEls=useRef(new Map<string,HTMLAudioElement>());
 async function load(){if(!supabase)return;const [{data:p},{data:e},{data:m}]=await Promise.all([supabase.from('team_posts').select('*').eq('team','voltigeurs').order('created_at',{ascending:false}),supabase.from('team_events').select('*').eq('team','voltigeurs').order('event_date'),supabase.from('ca_members').select('user_id,display_name,position,role,active').in('role',['coordinateur','charge_mission_voltigeurs','voltigeur']).eq('active',true).order('display_name')]);setPosts((p||[]) as Post[]);setEvents((e||[]) as Event[]);setMembers(m||[])}
 useEffect(()=>{void load();return()=>{stream.current?.getTracks().forEach(t=>t.stop());peers.current.forEach(pc=>pc.close());audioEls.current.forEach(a=>a.remove());if(radioChannel.current&&supabase)void supabase.removeChannel(radioChannel.current)}},[]);
 async function addPost(e:React.FormEvent){e.preventDefault();if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();const {data:m}=await supabase.from('ca_members').select('display_name').eq('user_id',user!.id).single();const {error}=await supabase.from('team_posts').insert({team:'voltigeurs',title,body,event_date:date||null,author_id:user!.id,author_name:m?.display_name||''});if(error)return toast.error(error.message);setTitle('');setBody('');setDate('');toast.success('Information partagée aux voltigeurs');void load()}
 async function addEvent(e:React.FormEvent){e.preventDefault();if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('team_events').insert({team:'voltigeurs',title,event_date:date,location,instructions:body,created_by:user!.id});if(error)return toast.error(error.message);setTitle('');setBody('');setDate('');setLocation('');toast.success('Événement ajouté');void load()}
 async function signal(kind:string,target:string|null,payload:any={}){if(!supabase||!me.current)return;await supabase.from('team_radio_signals').insert({team:'voltigeurs',room:selectedEvent,sender:me.current,target,kind,payload});}
 function dropPeer(id:string){peers.current.get(id)?.close();peers.current.delete(id);const a=audioEls.current.get(id);if(a){a.pause();a.remove();audioEls.current.delete(id)}setOnline(peers.current.size+1)}
 function peer(id:string){let pc=peers.current.get(id);if(pc)return pc;pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]});stream.current?.getTracks().forEach(t=>pc!.addTrack(t,stream.current!));pc.onicecandidate=e=>{if(e.candidate)void signal('ice',id,e.candidate.toJSON())};pc.ontrack=e=>{let a=audioEls.current.get(id);if(!a){a=document.createElement('audio');a.autoplay=true;a.setAttribute('playsinline','true');document.body.appendChild(a);audioEls.current.set(id,a)}a.srcObject=e.streams[0];void a.play().catch(()=>{})};pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(pc!.connectionState))dropPeer(id)};peers.current.set(id,pc);setOnline(peers.current.size+1);return pc}
 async function offer(id:string){const pc=peer(id);if(pc.signalingState!=='stable')return;const o=await pc.createOffer();await pc.setLocalDescription(o);await signal('offer',id,o)}
 async function handleSignal(row:any){if(!me.current||row.sender===me.current||row.room!==selectedEvent)return;const id=row.sender as string;if(row.kind==='join'){if(me.current<id)await offer(id);return}if(row.kind==='leave'){dropPeer(id);return}const pc=peer(id);try{if(row.kind==='offer'){await pc.setRemoteDescription(new RTCSessionDescription(row.payload));const a=await pc.createAnswer();await pc.setLocalDescription(a);await signal('answer',id,a)}else if(row.kind==='answer'){await pc.setRemoteDescription(new RTCSessionDescription(row.payload))}else if(row.kind==='ice'&&row.payload){await pc.addIceCandidate(new RTCIceCandidate(row.payload))}}catch(e){console.warn('Radio signal',e)}}
 async function joinAudio(){if(!supabase)return;try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw Error('session');me.current=user.id;const s=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});s.getAudioTracks().forEach(t=>t.enabled=false);stream.current=s;setMic(false);setRoom(selectedEvent==='general'?'Canal général Voltigeurs':events.find(e=>e.id===selectedEvent)?.title||'Canal Voltigeurs');const ch=supabase.channel('voltigeurs-radio-'+selectedEvent).on('postgres_changes',{event:'INSERT',schema:'public',table:'team_radio_signals',filter:'room=eq.'+selectedEvent},p=>{void handleSignal(p.new)}).subscribe(async status=>{if(status==='SUBSCRIBED'){setRadioStatus('Connecté');setJoined(true);setOnline(1);await signal('join',null);toast.success('Canal connecté — micro coupé par défaut.')}else if(status==='CHANNEL_ERROR'||status==='TIMED_OUT')setRadioStatus('Connexion interrompue')});radioChannel.current=ch}catch{toast.error("Impossible d'ouvrir le canal. Vérifiez l'autorisation du micro et la connexion.")}}
 function toggleMic(on:boolean){stream.current?.getAudioTracks().forEach(t=>t.enabled=on);setMic(on)}
 async function leave(){if(joined)await signal('leave',null);peers.current.forEach((_,id)=>dropPeer(id));stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(radioChannel.current&&supabase)await supabase.removeChannel(radioChannel.current);radioChannel.current=null;setJoined(false);setMic(false);setOnline(0);setRadioStatus('Hors ligne')}
 return <section><div className="member-admin-head"><div><p className="eyebrow">CORPS & ÉQUIPES · FFMC 06</p><h2>Voltigeurs</h2><p className="subtitle">Consignes, événements et communication opérationnelle.</p></div><span className="private">{manage?'Gestion Voltigeurs':'Voltigeur'}</span></div>
 <div className="filters"><button className={tab==='infos'?'chosen':''} onClick={()=>setTab('infos')}><FileText size={15}/> Informations</button><button className={tab==='events'?'chosen':''} onClick={()=>setTab('events')}><CalendarDays size={15}/> Événements</button><button className={tab==='members'?'chosen':''} onClick={()=>setTab('members')}><Users size={15}/> Équipe</button><button className={tab==='live'?'chosen':''} onClick={()=>setTab('live')}><Map size={15}/> Opération en direct</button><button className={tab==='radio'?'chosen':''} onClick={()=>setTab('radio')}><Radio size={15}/> Communication</button></div>
 {tab==='infos'&&<>{manage&&<form className="member-invite" onSubmit={addPost}><h3>Partager une information aux voltigeurs</h3><label>Titre<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Consigne / information<textarea required rows={4} value={body} onChange={e=>setBody(e.target.value)}/></label><label>Date liée (facultatif)<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="primary">Publier</button></form>}<div className="cards">{posts.map(p=><article className="record" key={p.id}><div className="record-top"><span className="badge">INFO VOLTIGEURS</span><small>{p.event_date||new Date(p.created_at).toLocaleDateString('fr-FR')}</small></div><h3>{p.title}</h3><p style={{whiteSpace:'pre-wrap'}}>{p.body}</p><div className="record-bottom"><span>{p.author_name||'FFMC 06'}</span></div></article>)}</div></>}
 {tab==='events'&&<>{manage&&<form className="member-invite" onSubmit={addEvent}><h3>Nouvel événement / dispositif</h3><label>Événement<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><div className="form-row"><label>Date<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Lieu<input value={location} onChange={e=>setLocation(e.target.value)}/></label></div><label>Consignes<textarea rows={4} value={body} onChange={e=>setBody(e.target.value)}/></label><button className="primary">Ajouter l’événement</button></form>}<div className="cards">{events.map(e=><article className="record" key={e.id}><div className="record-top"><span className="badge">{new Date(e.event_date+'T12:00:00').toLocaleDateString('fr-FR')}</span></div><h3>{e.title}</h3><p>{e.location}</p><p style={{whiteSpace:'pre-wrap'}}>{e.instructions}</p></article>)}</div></>}
 {tab==='members'&&<div className="cards">{members.map(m=><article className="record" key={m.user_id}><div className="record-top"><span className="badge">{m.role==='coordinateur'?'Coordinateur':m.role==='charge_mission_voltigeurs'?'Chargé de mission':'Voltigeur'}</span></div><h3>{m.display_name||'Membre FFMC 06'}</h3><p>{m.position||'Équipe Voltigeurs'}</p></article>)}</div>}
 {tab==='live'&&<Suspense fallback={<div className="meeting-prompt"><p>Chargement de la carte…</p></div>}><LiveOperation events={events} manage={manage}/></Suspense>}
 {tab==='radio'&&<div className="meeting-prompt" style={{maxWidth:620,margin:'20px auto',textAlign:'center'}}><Radio size={36}/><p className="eyebrow">COMMUNICATION MANIFESTATION</p><h2>{joined?room:'Canal Voltigeurs'}</h2><p>{joined?radioStatus+' · '+online+' connecté'+(online>1?'s':''):'Choisissez le canal puis connectez le téléphone avant le départ. Ne manipulez pas le téléphone en conduisant.'}</p>{!joined&&<label style={{display:'block',margin:'16px 0',textAlign:'left'}}>Canal<select value={selectedEvent} onChange={e=>setSelectedEvent(e.target.value)} style={{width:'100%',padding:12,marginTop:6}}><option value="general">Général Voltigeurs</option>{events.map(e=><option key={e.id} value={e.id}>{e.title} · {new Date(e.event_date+'T12:00:00').toLocaleDateString('fr-FR')}</option>)}</select></label>}{!joined?<button className="primary" onClick={joinAudio}><Mic size={20}/> Rejoindre le canal</button>:<><div style={{position:'sticky',bottom:12,zIndex:20,padding:'8px 0'}}><button aria-label={mic?'Couper le micro':'Ouvrir le micro'} onClick={()=>toggleMic(!mic)} style={{width:'100%',height:'min(58vh,430px)',minHeight:280,fontSize:'clamp(30px,9vw,54px)',fontWeight:950,borderRadius:32,border:mic?'4px solid currentColor':'4px solid transparent',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:18,touchAction:'manipulation',userSelect:'none',boxShadow:'0 12px 40px rgba(0,0,0,.16)'}} className={mic?'primary':'secondary'}>{mic?<><Mic size={64}/><span>MICRO ON</span><small style={{fontSize:16,fontWeight:700}}>TOUCHER POUR COUPER</small></>:<><MicOff size={64}/><span>MICRO OFF</span><small style={{fontSize:16,fontWeight:700}}>TOUCHER POUR PARLER</small></>}</button></div><p style={{fontSize:18}}><strong>{mic?'🔴 Vous transmettez':'Micro coupé'}</strong></p><button className="secondary" onClick={leave}>Quitter le canal</button></>}<div className="notice" style={{marginTop:20}}><Users size={18}/><span>Audio temps réel chiffré par WebRTC entre les appareils. Le canal utilise le compte FFMC connecté. Pour la sécurité, le micro démarre toujours coupé.</span></div></div>}
 </section>
}