import {useEffect,useState} from 'react';
import {Bell,CheckCircle2,Lightbulb,Vote,XCircle} from 'lucide-react';
import {supabase} from './lib/backend';
import {toast} from 'sonner';
type Proposal={id:string;author_id:string;author_name:string;title:string;body:string;status:string;coordinator_note?:string;created_at:string;closed_at?:string;outcome?:string;followup_kind?:string;followup_record_id?:string;result_summary?:string;event_date?:string};
type VoteRow={proposal_id:string;voter_id:string;choice:'pour'|'contre'|'abstention'};
type LegacyIdea={id:string;title:string;body:string;status:string;created_at:string;submitted_by?:string;proposal_id?:string};
export default function VotesBoard({isCoordinator=false}:{isCoordinator?:boolean}){
 const [items,setItems]=useState<Proposal[]>([]),[legacyIdeas,setLegacyIdeas]=useState<LegacyIdea[]>([]),[votes,setVotes]=useState<VoteRow[]>([]),[uid,setUid]=useState(''),[title,setTitle]=useState(''),[body,setBody]=useState(''),[busy,setBusy]=useState(false);
 async function load(){if(!supabase)return;const [{data:{user}},{data:p},{data:v},{data:i}]=await Promise.all([supabase.auth.getUser(),supabase.from('ca_proposals').select('*').order('created_at',{ascending:false}),supabase.from('ca_votes').select('proposal_id,voter_id,choice'),supabase.from('ca_ideas').select('id,title,body,status,created_at,submitted_by,proposal_id').is('proposal_id',null).order('created_at',{ascending:false})]);setUid(user?.id||'');setItems((p||[]) as Proposal[]);setVotes((v||[]) as VoteRow[]);setLegacyIdeas((i||[]) as LegacyIdea[]);}
 useEffect(()=>{void load();},[]);
 async function propose(e:React.FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);const {data:{user}}=await supabase.auth.getUser();const {data:m}=await supabase.from('ca_members').select('display_name').eq('user_id',user!.id).maybeSingle();const {error}=await supabase.from('ca_proposals').insert({author_id:user!.id,author_name:m?.display_name||'Membre du CA',title:title.trim(),body:body.trim()});setBusy(false);if(error)return toast.error(error.message);setTitle('');setBody('');toast.success('Proposition envoyée au coordinateur pour relecture.');await load();}
 function detectDate(text:string){const iso=text.match(/\b(20\d{2})[-\/.](0?[1-9]|1[0-2])[-\/.](0?[1-9]|[12]\d|3[01])\b/);if(iso)return `${iso[1]}-${String(iso[2]).padStart(2,'0')}-${String(iso[3]).padStart(2,'0')}`;const fr=text.match(/\b(0?[1-9]|[12]\d|3[01])[\/.-](0?[1-9]|1[0-2])[\/.-](20\d{2})\b/);return fr?`${fr[3]}-${String(fr[2]).padStart(2,'0')}-${String(fr[1]).padStart(2,'0')}`:'';}
 async function edit(p:Proposal){const t=prompt('Titre de la proposition',p.title);if(t===null)return;const b=prompt('Texte soumis au CA',p.body);if(b===null)return;const suggested=p.event_date||detectDate(t+' '+b);const date=prompt('Date liée à cette proposition (AAAA-MM-JJ). Laisser vide si aucune.',suggested);if(date===null)return;await patch(p,{title:t.trim(),body:b.trim(),event_date:date.trim()||undefined} as any);}
 async function patch(p:Proposal,changes:Partial<Proposal>){if(!supabase)return;setBusy(true);const {error}=await supabase.from('ca_proposals').update({...changes,updated_at:new Date().toISOString()}).eq('id',p.id);setBusy(false);if(error)return toast.error(error.message);toast.success(changes.status==='voting'?'Vote ouvert.':changes.status==='closed'?'Vote clôturé.':'Proposition mise à jour.');await load();}
 async function publishIdea(i:LegacyIdea){if(!supabase||!uid)return;setBusy(true);const t=prompt('Relire / modifier le titre avant le vote',i.title);if(t===null){setBusy(false);return;}const b=prompt('Relire / modifier le texte qui sera soumis au vote',i.body);if(b===null){setBusy(false);return;}const {data:m}=await supabase.from('ca_members').select('display_name').eq('user_id',i.submitted_by||uid).maybeSingle();const {data:p,error}=await supabase.from('ca_proposals').insert({author_id:i.submitted_by||uid,author_name:m?.display_name||'Membre du CA',title:t.trim(),body:b.trim(),status:'voting',event_date:detectDate(t+' '+b)||null}).select('id').single();if(error){setBusy(false);return toast.error(error.message);}const {error:linkError}=await supabase.from('ca_ideas').update({status:'Soumise au vote',proposal_id:p.id,reviewed_at:new Date().toISOString()}).eq('id',i.id);setBusy(false);if(linkError)return toast.error(linkError.message);toast.success('Idée publiée : le vote est maintenant ouvert au CA.');await load();}
 async function rejectIdea(i:LegacyIdea){if(!supabase)return;const {error}=await supabase.from('ca_ideas').update({status:'Refusée',reviewed_at:new Date().toISOString()}).eq('id',i.id);if(error)return toast.error(error.message);toast.success('Idée classée comme refusée.');await load();}
 async function closeVote(p:Proposal){if(!supabase)return;const pour=count(p.id,'pour'),contre=count(p.id,'contre'),abst=count(p.id,'abstention'),total=pour+contre+abst;const outcome=pour>contre?'Adoptée':contre>pour?'Rejetée':'Égalité / décision à confirmer';const summary=`Vote clôturé le ${new Date().toLocaleDateString('fr-FR')} — ${total} votant(s) : ${pour} Pour, ${contre} Contre, ${abst} Abstention(s). Résultat : ${outcome}.`;const {error}=await supabase.from('ca_proposals').update({status:'closed',closed_at:new Date().toISOString(),outcome,result_summary:summary,updated_at:new Date().toISOString()}).eq('id',p.id);if(error)return toast.error(error.message);if(p.event_date){const {data:existing}=await supabase.from('records').select('id').eq('title',p.title).eq('due',p.event_date).limit(1);if(!existing?.length)await supabase.from('records').insert({kind:'Dossier',title:p.title,status:'En cours',owner:'',due:p.event_date,notes:`${p.body}\n\nCOMPTE RENDU DU VOTE\n${summary}`,next:'Échéance issue d’une décision du CA'});}toast.success(p.event_date?'Vote clôturé et date ajoutée automatiquement à l’agenda.':'Vote clôturé. Choisis maintenant comment suivre cette décision.');await load();}
 async function followUp(p:Proposal,kind:'Dossier'|'Réunion'|'Agenda'|'Archive'){if(!supabase)return;let recordId:string|undefined;if(kind!=='Archive'){const due=kind==='Agenda'?prompt('Date à ajouter à l’agenda (AAAA-MM-JJ)',new Date().toISOString().slice(0,10)):'';if(kind==='Agenda'&&due===null)return;const recordKind=kind==='Réunion'?'Réunion':'Dossier';const {data,error}=await supabase.from('records').insert({kind:recordKind,title:p.title,status:kind==='Réunion'?'À réfléchir':'En cours',owner:'',due:due||'',notes:`${p.body}\n\nCOMPTE RENDU DU VOTE\n${p.result_summary||''}`,next:kind==='Agenda'?'À traiter à la date prévue':'Décision du CA à mettre en œuvre'}).select('id').single();if(error)return toast.error(error.message);recordId=data?.id;}const {error}=await supabase.from('ca_proposals').update({followup_kind:kind,followup_record_id:recordId||null,updated_at:new Date().toISOString()}).eq('id',p.id);if(error)return toast.error(error.message);toast.success(kind==='Archive'?'Décision archivée dans le compte rendu des votes.':`Suivi créé : ${kind}.`);await load();}
 async function cast(p:Proposal,choice:VoteRow['choice']){if(!supabase||p.status!=='voting')return;setBusy(true);const {error}=await supabase.from('ca_votes').upsert({proposal_id:p.id,voter_id:uid,choice,updated_at:new Date().toISOString()},{onConflict:'proposal_id,voter_id'});setBusy(false);if(error)return toast.error(error.message);toast.success('Votre vote est enregistré.');await load();}
 const count=(id:string,c:VoteRow['choice'])=>votes.filter(v=>v.proposal_id===id&&v.choice===c).length;
 const label=(s:string)=>({review:'À relire',approved:'Validée',rejected:'Refusée',voting:'Vote en cours',closed:'Vote clôturé'} as any)[s]||s;
 return <section className="space-y-5"><div className="flex flex-wrap justify-between gap-4 items-start"><div><p className="text-xs font-bold tracking-wider text-red-700">DÉMOCRATIE DU CA</p><h2 className="text-2xl font-extrabold">Idées, résolutions & votes</h2><p className="text-sm text-slate-500">Une idée est relue avant d’être soumise au vote du conseil d’administration.</p></div></div>
 <form onSubmit={propose} className="p-5 rounded-xl bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 space-y-3"><h3 className="font-bold flex gap-2 items-center"><Lightbulb size={18}/> Proposer une idée</h3><input required maxLength={200} className="w-full rounded-lg border p-2.5 dark:bg-zinc-950 dark:border-zinc-700" placeholder="Titre de la proposition" value={title} onChange={e=>setTitle(e.target.value)}/><textarea required maxLength={10000} rows={4} className="w-full rounded-lg border p-2.5 dark:bg-zinc-950 dark:border-zinc-700" placeholder="Expliquez l’idée, son objectif et ce que vous proposez au CA…" value={body} onChange={e=>setBody(e.target.value)}/><button disabled={busy} className="px-4 py-2 rounded-lg bg-red-700 text-white font-semibold">Envoyer pour relecture</button></form>
 {isCoordinator&&legacyIdeas.length>0&&<div className="space-y-3"><h3 className="text-lg font-bold">Idées des membres à relire</h3><p className="text-sm text-slate-500">Rien n'est publié au vote sans ta relecture. Tu peux modifier le titre et le texte juste avant de l'ouvrir.</p>{legacyIdeas.map(i=><article key={i.id} className="p-5 rounded-xl bg-amber-50 border border-amber-200 space-y-3"><span className="text-xs font-bold">À RELIRE</span><h3 className="font-bold">{i.title}</h3><p className="whitespace-pre-wrap">{i.body}</p><div className="flex gap-2 flex-wrap"><button disabled={busy} onClick={()=>publishIdea(i)} className="px-3 py-2 rounded-lg bg-green-700 text-white text-xs font-semibold">Relire puis publier au vote</button><button disabled={busy} onClick={()=>rejectIdea(i)} className="px-3 py-2 rounded-lg border text-xs font-semibold">Refuser / classer</button></div></article>)}</div>}
 <div className="grid gap-4">{items.map(p=>{const mine=votes.find(v=>v.proposal_id===p.id&&v.voter_id===uid);return <article key={p.id} className="p-5 rounded-xl bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 space-y-3"><div className="flex justify-between gap-3"><div><span className="text-xs font-bold text-red-700">{label(p.status)}</span><h3 className="text-lg font-bold">{p.title}</h3><small className="text-slate-500">Proposé par {p.author_name}</small></div><Vote size={22}/></div><p className="text-sm whitespace-pre-wrap">{p.body}</p>
 {p.status==='voting'||p.status==='closed'?<div className="grid sm:grid-cols-3 gap-2"><button disabled={busy||p.status!=='voting'} onClick={()=>cast(p,'pour')} className={'rounded-lg border p-3 '+(mine?.choice==='pour'?'ring-2 ring-green-600':'')}><strong>Pour</strong><br/><span>{count(p.id,'pour')} vote(s)</span></button><button disabled={busy||p.status!=='voting'} onClick={()=>cast(p,'contre')} className={'rounded-lg border p-3 '+(mine?.choice==='contre'?'ring-2 ring-red-600':'')}><strong>Contre</strong><br/><span>{count(p.id,'contre')} vote(s)</span></button><button disabled={busy||p.status!=='voting'} onClick={()=>cast(p,'abstention')} className={'rounded-lg border p-3 '+(mine?.choice==='abstention'?'ring-2 ring-slate-500':'')}><strong>Abstention</strong><br/><span>{count(p.id,'abstention')} vote(s)</span></button></div>:null}
 {p.status==='closed'&&p.result_summary&&<div className="rounded-lg bg-slate-50 dark:bg-zinc-800 p-3 text-sm"><strong>Compte rendu du vote</strong><p>{p.result_summary}</p>{p.followup_kind&&<small>Suivi : {p.followup_kind}</small>}</div>}
 {isCoordinator&&p.status==='closed'&&!p.followup_kind&&<div className="rounded-lg border border-amber-200 bg-amber-50 p-3 space-y-2"><strong className="text-sm">Que fait-on de cette décision ?</strong><p className="text-xs text-slate-600">Le compte rendu du vote est déjà conservé. Choisis son suivi opérationnel.</p><div className="flex flex-wrap gap-2"><button onClick={()=>followUp(p,'Dossier')} className="px-3 py-2 rounded-lg border bg-white text-xs font-semibold">Créer un dossier / action</button><button onClick={()=>followUp(p,'Agenda')} className="px-3 py-2 rounded-lg border bg-white text-xs font-semibold">Ajouter à l’agenda</button><button onClick={()=>followUp(p,'Réunion')} className="px-3 py-2 rounded-lg border bg-white text-xs font-semibold">Préparer pour une réunion</button><button onClick={()=>followUp(p,'Archive')} className="px-3 py-2 rounded-lg border bg-white text-xs font-semibold">Archiver la décision</button></div></div>}
 {isCoordinator&&<div className="flex flex-wrap gap-2 pt-2 border-t dark:border-zinc-800"><button onClick={()=>edit(p)} className="px-3 py-2 rounded-lg border text-xs font-semibold">Modifier / relire</button>{p.status==='review'&&<><button onClick={()=>patch(p,{status:'voting'})} className="px-3 py-2 rounded-lg bg-green-700 text-white text-xs font-semibold"><CheckCircle2 size={14} className="inline"/> Valider et ouvrir le vote</button><button onClick={()=>patch(p,{status:'rejected'})} className="px-3 py-2 rounded-lg border text-xs font-semibold"><XCircle size={14} className="inline"/> Refuser</button></>}{p.status==='voting'&&<button onClick={()=>closeVote(p)} className="px-3 py-2 rounded-lg bg-slate-900 text-white text-xs font-semibold">Clôturer le vote</button>}</div>}</article>})}</div></section>;
}
export function NotificationsPanel({onNavigate}:{onNavigate:(tab:string)=>void}){
 const [items,setItems]=useState<any[]>([]);
 async function load(){if(!supabase)return;const {data}=await supabase.from('ca_notifications').select('*').order('created_at',{ascending:false}).limit(100);setItems(data||[])} useEffect(()=>{void load()},[]);
 async function read(n:any){if(!supabase)return;if(!n.read_at)await supabase.from('ca_notifications').update({read_at:new Date().toISOString()}).eq('id',n.id);if(n.target_tab)onNavigate(n.target_tab);await load();}
 return <section className="space-y-4"><div><p className="text-xs font-bold tracking-wider text-red-700">CENTRE DU CA</p><h2 className="text-2xl font-extrabold flex gap-2 items-center"><Bell/> Notifications</h2><p className="text-sm text-slate-500">Votes, propositions et informations qui demandent votre attention.</p></div><div className="grid gap-2">{items.length?items.map(n=><button key={n.id} onClick={()=>read(n)} className={'text-left p-4 rounded-xl border bg-white dark:bg-zinc-900 dark:border-zinc-800 '+(!n.read_at?'ring-1 ring-red-600':'opacity-70')}><strong>{n.title}</strong><p className="text-sm">{n.body}</p><small>{new Date(n.created_at).toLocaleString('fr-FR')}</small></button>):<p className="p-5 rounded-xl bg-white dark:bg-zinc-900">Aucune notification pour le moment.</p>}</div></section>;
}