import {useMemo,useState} from 'react';
import {FileText,Image as ImageIcon,MessageCircle,Upload,Check} from 'lucide-react';
import {supabase} from './lib/backend';
import {toast} from 'sonner';
type Msg={date:string;author:string;text:string};
const rx=/^(?:\[)?(\d{1,2}[\/.-]\d{1,2}[\/.-]\d{2,4})[, ]+\s*(\d{1,2}:\d{2})(?:\])?\s*[-–]\s*([^:]+):\s*(.*)$/;
function parseWhatsApp(text:string){const out:Msg[]=[];let current:Msg|null=null;for(const raw of text.replace(/\r/g,'').split('\n')){const m=raw.match(rx);if(m){current={date:m[1]+' '+m[2],author:m[3].trim(),text:m[4].trim()};out.push(current)}else if(current&&raw.trim())current.text+='\n'+raw.trim()}return out}
const interesting=(m:Msg)=>/idée|propos|faudrait|pourrait|devrait|réunion|ca\b|action|manifest|ct\b|calmos|rendez-vous|organis|décid|vote|préfecture|communication|affiche|bénévole|formation/i.test(m.text);
export default function WhatsAppImport(){const [files,setFiles]=useState<File[]>([]),[messages,setMessages]=useState<Msg[]>([]),[selected,setSelected]=useState<Set<number>>(new Set()),[busy,setBusy]=useState(false);const media=useMemo(()=>files.filter(f=>f.type.startsWith('image/')),[files]);
async function load(list:FileList|null){if(!list)return;const all=Array.from(list);setFiles(all);const txt=all.find(f=>f.name.toLowerCase().endsWith('.txt'));if(!txt){setMessages([]);toast.error('Ajoute le fichier .txt exporté par WhatsApp.');return}const parsed=parseWhatsApp(await txt.text());setMessages(parsed);setSelected(new Set(parsed.map((m,i)=>interesting(m)?i:-1).filter(i=>i>=0)))}
async function addIdeas(){if(!supabase||!selected.size)return;setBusy(true);try{const rows=[...selected].map(i=>messages[i]).filter(Boolean).map(m=>({title:`WhatsApp · ${m.author}`,body:`${m.date}\n\n${m.text}`,status:'Proposée'}));const {error}=await supabase.from('ca_ideas').insert(rows);if(error)throw error;toast.success(`${rows.length} élément(s) ajouté(s) aux idées du CA.`);setSelected(new Set())}catch{toast.error('Impossible d’ajouter les éléments sélectionnés.')}finally{setBusy(false)}}
return <section><div className="ca-title"><p className="eyebrow">IMPORT DE DISCUSSION</p><h1>WhatsApp du CA</h1><p className="subtitle">Exporte la discussion WhatsApp avec les médias, puis sélectionne ici le fichier .txt et les images. Rien n’est ajouté au CA sans validation.</p></div><label className="meeting-prompt" style={{display:'block',cursor:'pointer'}}><Upload size={28}/><h2>Importer l’export WhatsApp</h2><p>Sélectionne le fichier texte et tous les médias de l’export. Les images restent visibles pendant la revue.</p><input hidden type="file" multiple accept=".txt,image/*" onChange={e=>void load(e.target.files)}/><span className="secondary" style={{display:'inline-flex',padding:'10px 14px'}}>Choisir les fichiers</span></label>{!!files.length&&<div className="ca-metrics below"><div><strong>{messages.length}</strong><span>messages lus</span></div><div><strong>{media.length}</strong><span>images détectées</span></div><div><strong>{selected.size}</strong><span>éléments proposés</span></div></div>}{!!media.length&&<><h2 className="below"><ImageIcon size={20}/> Images de la discussion</h2><div className="member-grid">{media.slice(0,12).map((f,i)=><article className="member-card" key={f.name+i}><img src={URL.createObjectURL(f)} alt={f.name} style={{width:'100%',maxHeight:220,objectFit:'contain',borderRadius:8}}/><small>{f.name}</small></article>)}</div></>}{!!messages.length&&<><div className="section-head below"><div><h2>Idées, débats et actions détectés</h2><p className="muted">Une présélection est faite à partir des sujets d’action. Vérifie avant d’ajouter.</p></div><button className="primary" disabled={!selected.size||busy} onClick={addIdeas}><Check size={16}/>{busy?'Ajout…':`Ajouter la sélection (${selected.size})`}</button></div><div className="cards">{messages.map((m,i)=>interesting(m)||selected.has(i)?<button key={i} className="record" onClick={()=>setSelected(s=>{const n=new Set(s);n.has(i)?n.delete(i):n.add(i);return n})}><div className="record-top"><span className="badge">{selected.has(i)?'Sélectionné':'Ignoré'}</span><MessageCircle size={17}/></div><h3>{m.author}</h3><p style={{whiteSpace:'pre-wrap'}}>{m.text}</p><div className="record-bottom"><span><FileText size={13}/> WhatsApp</span><span>{m.date}</span></div></button>:null)}</div></>}</section>}